"""Stage 5a: standardized dish-image prompt assembly.

Owns the FIXED template text (ported verbatim from the Founder-supplied reference,
`FooFoo_Dish_Image_Prompts_v2.xlsx`, confirmed against 5 rows: Butter Chicken, Dal Makhani,
Sarson Ka Saag, Makki Ki Roti, Tandoori Chicken — the template held with no variation across all
five; only the fill-in blanks change). The LLM backend (Groq primary, Hugging Face Inference API
alternate, deterministic heuristic last-resort) supplies ONLY the four blanks:
  - category            (cuisine/course-style label, e.g. "North Indian Gravy")
  - vessel_type         (serving vessel, e.g. "copper bowl")
  - visual_description  (2-3 sentences: appearance, colors, texture, garnish, accompaniment)
  - color_focal_point    (2-3 words, e.g. "rich orange-red gravy")
The template text itself is never generated by the model — this is deliberate so prompt output
format cannot drift dish-to-dish (task brief requirement).

Every result is tagged with its real source ('groq_api' | 'hf_api' | 'heuristic') — same honesty
discipline as groq_adapter.py: never claim a real model call that did not happen. Network is only
reached when the corresponding API key is actually configured.
"""

from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from dataclasses import dataclass

logger = logging.getLogger("dish_ingestion.image_prompt")

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
# Deliberately a larger model than groq_adapter.py's region/tag classification (llama-3.1-8b-
# instant is fine for short classification tasks, but proved too shallow for grounding a dish's
# real cooked color/texture in its cooking method -- see IMAGE_PROMPT_GROQ_MODEL_CHANGE note in
# the runbook: it described Masala Karela as "bright yellow" from seeing "turmeric" in the
# ingredient list, when the real dish (roasted with red chilli powder) is dark reddish-brown/
# near-black, confirmed against a Founder-supplied reference photo). Own env var, not shared with
# groq_adapter.py's GROQ_MODEL, so tuning one doesn't silently retune the other.
GROQ_MODEL = os.environ.get("IMAGE_PROMPT_GROQ_MODEL", "llama-3.3-70b-versatile")

# Hugging Face's legacy `api-inference.huggingface.co` endpoint was fully retired in favor of the
# Inference Providers router (https://router.huggingface.co) — the old host no longer resolves for
# some callers and returns 410 Gone for others. The router speaks the OpenAI-compatible chat
# completions shape, same as the Groq call above, rather than the old raw text-generation payload.
HF_MODEL = os.environ.get("HF_MODEL", "mistralai/Mistral-7B-Instruct-v0.3")
HF_API_URL = "https://router.huggingface.co/v1/chat/completions"

# The exact standardized template, ported literally from the xlsx `prompt` column -- re-verified
# character-for-character against Butter Chicken's actual cell content this session (the only
# difference was the xlsx's mojibake-encoded em dash "â€”" vs a real "—" here, an xlsx encoding
# artifact, not a content difference). {dish_name} and the four LLM-sourced blanks are the only
# variable slots; every other word is fixed, byte-for-byte, dish to dish. A short, tag-style
# variant was tried and also failed to fix bad results on unfamiliar dishes (see git history,
# reverted) -- reverting to this exact reference form rather than continuing to improvise
# variations away from it.
#
# One deliberate addition beyond the reference: "(a fully cooked, prepared, plated dish, ready to
# eat)" right after {dish_name}. Founder-confirmed real failure: Masala Karela rendered as a bowl
# of RAW, uncut bitter gourd -- the reference's 867 sample dishes are all named after already-
# cooked concepts ("gravy", "roti", "chicken curry") so this ambiguity never came up for them, but
# any dish named directly after a raw vegetable/ingredient (karela, methi, etc.) has no built-in
# "this is cooked" signal otherwise, and the model defaults to its strongest prior: the raw
# ingredient. This phrase is a fixed, guaranteed anchor independent of what the LLM-generated
# visual_description says.
PROMPT_TEMPLATE = (
    "Generate a high-quality professional food photograph of {dish_name} (a fully cooked, "
    "prepared, plated dish, ready to eat -- never raw or uncut ingredients): {visual_description}. "
    "Served in a traditional {vessel_type}. The table surface is a clean warm-toned rustic wooden "
    "board with nothing else on it — no scattered spices, no loose herbs, no cloth, no glass, "
    "no items that are not part of the dish. Only the dish and its actual accompaniments. "
    "Photography style: 45-degree angle, soft natural window light from the left side, warm color "
    "temperature, shallow depth of field with a softly blurred background, appetizing steam rising "
    "gently. The colors should draw attention to {color_focal_point}. The image should look like "
    "premium editorial food photography — ultra sharp, high resolution, clean composition. "
    "Aspect ratio 16:9."
)


def clean_dish_name_for_prompt(raw_name: str) -> str:
    """Strips CSV article-title cruft down to a plain dish name for image-prompt use, matching
    the Founder-supplied reference (FooFoo_Dish_Image_Prompts_v2.xlsx): its dish_name column is
    always a clean name like "Butter Chicken" or "Tomato Rice", never a raw recipe-article title.

    The raw CSV RecipeName/TranslatedRecipeName are article titles, not dish names, and often
    carry both: a bilingual "<Devanagari> - <English>" pairing (e.g. "टमाटर पुलियोगरे रेसिपी -
    Spicy Tomato Rice (Recipe In Hindi)") and/or a trailing "Recipe" / "(Recipe In Hindi)" /
    "(Recipe)" suffix (e.g. "Masala Karela Recipe", "Maa Ki Dal Recipe"). Sent verbatim into an
    English-centric text-to-image model, both confuse it -- this is applied only to the string
    used inside the image prompt, never to the dish's canonical/database name.
    """
    import re

    name = raw_name.strip()
    if " - " in name:
        left, right = name.split(" - ", 1)
        if any(ord(ch) > 127 for ch in left):  # left side is non-Latin script -> keep the English side
            name = right
    name = re.sub(r"\s*\(recipe[^)]*\)\s*$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\s+recipe\s*$", "", name, flags=re.IGNORECASE)
    return name.strip() or raw_name.strip()


@dataclass
class PromptFields:
    category: str
    vessel_type: str
    visual_description: str
    color_focal_point: str
    source: str            # 'groq_api' | 'hf_api' | 'heuristic'
    model_name: str | None
    raw_response: dict | None


def assemble_prompt(dish_name: str, fields: PromptFields) -> str:
    """Server-owned assembly: the LLM never sees or produces the template text itself."""
    # The template already appends "." after {visual_description}; strip any trailing period the
    # LLM's own text ends with so real output never doubles up ("...alongside..").
    description = fields.visual_description.strip().rstrip(".")
    return PROMPT_TEMPLATE.format(
        dish_name=dish_name,
        visual_description=description,
        vessel_type=fields.vessel_type,
        color_focal_point=fields.color_focal_point,
    )


class ImagePromptGenerator:
    """Resolves the four fill-in fields for a dish, preferring Groq, then Hugging Face, then a
    deterministic heuristic — same pluggable-backend spirit as GroqAdapter in groq_adapter.py.
    """

    def __init__(self, groq_api_key: str | None = None, hf_api_key: str | None = None):
        self.groq_api_key = groq_api_key if groq_api_key is not None else os.environ.get("GROQ_API_KEY")
        self.hf_api_key = (
            hf_api_key
            if hf_api_key is not None
            else (os.environ.get("HF_API_KEY") or os.environ.get("HUGGINGFACE_API_KEY"))
        )

    def resolve_fields(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                        ingredients: list[str], force_heuristic: bool = False,
                        instructions: str | None = None) -> PromptFields:
        if force_heuristic:
            return self._heuristic(dish_name, cuisine_raw, course_raw, ingredients)
        if self.groq_api_key:
            try:
                return self._call_groq(dish_name, cuisine_raw, course_raw, ingredients, instructions)
            except Exception as exc:  # pragma: no cover - network
                logger.warning("groq prompt-field call failed for %s: %s; falling back", dish_name, exc)
        if self.hf_api_key:
            try:
                return self._call_hf(dish_name, cuisine_raw, course_raw, ingredients, instructions)
            except Exception as exc:  # pragma: no cover - network
                logger.warning("hf prompt-field call failed for %s: %s; falling back to heuristic", dish_name, exc)
        return self._heuristic(dish_name, cuisine_raw, course_raw, ingredients)

    # -- heuristic fallback (no network, no key required) --------------------------------------
    def _heuristic(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                    ingredients: list[str]) -> PromptFields:
        category = " ".join(x for x in [cuisine_raw, course_raw] if x).strip() or "Indian dish"
        vessel_type = "serving bowl"
        top_ingredients = ", ".join(ingredients[:4]) if ingredients else "its traditional ingredients"
        visual_description = (
            f"{dish_name}, prepared with {top_ingredients}, presented with its typical color, "
            "texture and garnish, served with its usual accompaniment"
        )
        color_focal_point = "the dish's natural color and texture"
        return PromptFields(
            category=category, vessel_type=vessel_type, visual_description=visual_description,
            color_focal_point=color_focal_point, source="heuristic", model_name=None,
            raw_response={"method": "deterministic_heuristic", "note": "no GROQ_API_KEY/HF key configured"},
        )

    # -- Groq backend ----------------------------------------------------------------------------
    def _call_groq(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                    ingredients: list[str], instructions: str | None = None) -> PromptFields:
        prompt = _fields_prompt(dish_name, cuisine_raw, course_raw, ingredients, instructions)
        payload = {
            "model": GROQ_MODEL,
            "messages": [
                {"role": "system", "content": "Return concise JSON only, no prose, no markdown fences."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 300,
        }
        req = urllib.request.Request(
            GROQ_API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.groq_api_key}", "Content-Type": "application/json",
                # see groq_adapter.py's same header for why this is required, not cosmetic.
                "User-Agent": "foofoo-dish-ingestion/1.0",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=25) as resp:  # pragma: no cover - network
            raw = json.loads(resp.read().decode("utf-8"))
        content = raw["choices"][0]["message"]["content"].strip()
        data = _parse_fields_json(content)
        return PromptFields(
            category=data["category"], vessel_type=data["vessel_type"],
            visual_description=data["visual_description"], color_focal_point=data["color_focal_point"],
            source="groq_api", model_name=GROQ_MODEL, raw_response=raw,
        )

    # -- Hugging Face Inference Providers router (alternate/fallback) ----------------------------
    def _call_hf(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                 ingredients: list[str], instructions: str | None = None) -> PromptFields:
        prompt = _fields_prompt(dish_name, cuisine_raw, course_raw, ingredients, instructions)
        # OpenAI-compatible chat completions shape (router.huggingface.co), not the retired
        # raw text-generation `{"inputs": ...}` payload the old api-inference host accepted.
        payload = {
            "model": HF_MODEL,
            "messages": [
                {"role": "system", "content": "Return concise JSON only, no prose."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 300,
        }
        req = urllib.request.Request(
            HF_API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.hf_api_key}", "Content-Type": "application/json",
                "User-Agent": "foofoo-dish-ingestion/1.0",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:  # pragma: no cover - network
            raw = json.loads(resp.read().decode("utf-8"))
        content = raw["choices"][0]["message"]["content"].strip()
        data = _parse_fields_json(content)
        return PromptFields(
            category=data["category"], vessel_type=data["vessel_type"],
            visual_description=data["visual_description"], color_focal_point=data["color_focal_point"],
            source="hf_api", model_name=HF_MODEL, raw_response=raw,
        )


_FIELD_METHOD_INSTRUCTIONS = """You are filling in 4 blanks for a food-photography prompt template. Study this method,
learned from 867 professionally hand-written examples for this same product, before answering:

0. If the dish name is itself a raw ingredient/vegetable name (karela/bitter gourd, methi/
   fenugreek, gobi/cauliflower, etc.), visual_description's FIRST WORDS must make cooked state
   explicit and unmistakable -- "Cooked and stir-fried..." / "Roasted and spiced..." -- never
   open with a bare color+shape description that could just as easily describe the raw
   vegetable. Confirmed real failure: "Masala Karela" without this rendered as a bowl of raw,
   uncut bitter gourd, because nothing in the description ruled that reading out.
1. visual_description opens with the dish's PHYSICAL FORM (an explicit SHAPE word: round coin-
   shaped slices, whole pods, small cubes, thin strands, a flat disc, individual florets --
   pick the one that actually matches how this ingredient is cut/shaped in this dish) + PRECISE
   COLOR + TEXTURE of its main component, derived from what the ingredients/cooking method
   actually produce -- never a vague "delicious" or "tasty". An image model with no training
   data for an unfamiliar regional vegetable/dish will guess a generic, wrong shape (e.g.
   noodle strands, or a shapeless mound) unless the shape is stated explicitly and unambiguously
   -- do not assume "slices" alone is enough; say what the slice actually looks like (thin round
   coins with visible seeds and a ridged green-going-brown skin, for example, is a real bitter
   gourd/karela slice -- adapt precisely to the actual vegetable, do not reuse this verbatim).
   Turmeric/gram-flour dishes are yellow; tomato-butter gravies are orange-red; slow-cooked dals
   are dark brown; coconut-based preparations are pale white/cream; charred/tandoor items are
   red-orange or dark with visible char marks.
2. It then names ONE OR TWO visible cues that prove HOW it was cooked -- a glossy sheen, char
   marks, froth, a crisp/flaky edge, steam, spiraled/folded shape -- specific to this dish's real
   preparation, not generic.
3. It then names the REAL, traditional garnish and the REAL, traditional accompaniment for this
   exact dish by name (e.g. "buttered naan alongside", "raita alongside", "appam alongside") --
   never invent one; if you are not confident of a traditional accompaniment for this dish, omit
   that clause rather than guessing.
4. vessel_type is the culturally-authentic serving vessel for this dish's real regional cuisine
   (steel tumbler+dabarah for filter coffee, banana leaf for a South Indian meal, copper handi for
   a slow-cooked North Indian gravy, bamboo steamer for momos) -- default to "steel plate" or
   "steel bowl" only when no more specific vessel is traditional.
5. color_focal_point is 3-6 words naming the single most eye-catching visual element with its
   color, e.g. "the rich orange-red gravy and golden chicken pieces" or "the yellow spiraled
   rolls with sesame-coconut topping" -- not a generic restatement of the dish name.

Two real examples of the expected depth and style (for calibration only, not this dish):

Example 1 -- Dal Makhani (North Indian Dal, copper handi):
"Rich dark brown creamy lentil preparation made with whole black urad dal and rajma, slow-cooked
to a thick glossy consistency. A generous swirl of fresh cream on top with a pat of golden butter
melting. Garnished with coriander. Buttered naan alongside." focal: "the dark rich dal with cream
and butter contrast"

Example 2 -- Khandvi (Gujarati, steel plate):
"Thin yellow rolled gram flour sheets tightly rolled into small spirals, topped with tempering of
mustard seeds, sesame seeds, curry leaves, and grated coconut. Neat and uniform." focal: "the
yellow spiraled rolls with sesame-coconut topping"
"""


def _fields_prompt(dish_name: str, cuisine_raw: str | None, course_raw: str | None, ingredients: list[str],
                    instructions: str | None = None) -> str:
    ing_text = ", ".join(ingredients[:12]) if ingredients else "unknown"
    # Truncated, not the full method -- enough for the model to see the actual cooking technique
    # (roasted/fried/simmered/steamed, which spices go in when) without ballooning token cost.
    instr_text = (instructions or "unknown").strip().replace("\n", " ")[:600]
    return (
        _FIELD_METHOD_INSTRUCTIONS +
        "\nCRITICAL — color must come from real-world cooking knowledge, not ingredient-name "
        "guessing: reason about what the dish actually looks like ONCE FULLY COOKED, from the "
        "combination of every spice/technique in the instructions, not the single most "
        "colorful-sounding raw ingredient. A raw spice's own color is not the finished dish's "
        "color. Concretely: red chilli powder + roasting/frying typically darkens a dish to deep "
        "reddish-brown or near-black at the edges, not the pale yellow of turmeric alone; slow "
        "browning/caramelizing darkens further; a dish simmered briefly in a wet gravy stays "
        "closer to its raw ingredient colors. If you are not confident, describe the dominant "
        "true color conservatively (e.g. \"deep reddish-brown\") rather than defaulting to a "
        "bright primary color that is not actually correct for this preparation.\n"
        f"\nNow apply this method to: Indian dish '{dish_name}' (cuisine: '{cuisine_raw or 'unknown'}', "
        f"course: '{course_raw or 'unknown'}', key ingredients: {ing_text}, cooking method: {instr_text}).\n"
        "Respond with JSON only, exactly these keys: "
        '"category" (short cuisine/course label, e.g. "North Indian Gravy"), '
        '"vessel_type" (culturally-authentic traditional serving vessel per rule 4 above), '
        '"visual_description" (2-3 sentences following rules 1-3 above), '
        '"color_focal_point" (3-6 words per rule 5 above). '
        "No prose outside the JSON object."
    )


def _parse_fields_json(content: str) -> dict:
    # Strip accidental markdown fences some models add despite instructions.
    text = content.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
    data = json.loads(text)
    for key in ("category", "vessel_type", "visual_description", "color_focal_point"):
        if key not in data or not data[key]:
            raise ValueError(f"model response missing required field '{key}'")
    return data
