"""Stage 5a: standardized dish-image prompt assembly.

Owns the FIXED template text (ported verbatim from the Founder-supplied reference,
`FooFoo_Dish_Image_Prompts_v2.xlsx`, confirmed against 5 rows: Butter Chicken, Dal Makhani,
Sarson Ka Saag, Makki Ki Roti, Tandoori Chicken — the template held with no variation across all
five; only the fill-in blanks change). The LLM backend (Groq primary, Hugging Face Inference API
alternate, deterministic heuristic last-resort) supplies ONLY the four blanks:
  - category            (cuisine/course-style label, e.g. "North Indian Gravy")
  - vessel_type         (serving vessel, e.g. "copper bowl")
  - visual_description  (2-3 sentences: appearance, colors, texture, garnish, accompaniment)
  - color_focal_point    (2-3 words, e.g. "rich orange-red gravy")
The template text itself is never generated by the model — this is deliberate so prompt output
format cannot drift dish-to-dish (task brief requirement).

Every result is tagged with its real source ('groq_api' | 'hf_api' | 'heuristic') — same honesty
discipline as groq_adapter.py: never claim a real model call that did not happen. Network is only
reached when the corresponding API key is actually configured.
"""

from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from dataclasses import dataclass

logger = logging.getLogger("dish_ingestion.image_prompt")

GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.1-8b-instant")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Hugging Face's legacy `api-inference.huggingface.co` endpoint was fully retired in favor of the
# Inference Providers router (https://router.huggingface.co) — the old host no longer resolves for
# some callers and returns 410 Gone for others. The router speaks the OpenAI-compatible chat
# completions shape, same as the Groq call above, rather than the old raw text-generation payload.
HF_MODEL = os.environ.get("HF_MODEL", "mistralai/Mistral-7B-Instruct-v0.3")
HF_API_URL = "https://router.huggingface.co/v1/chat/completions"

# The exact standardized template, ported literally from the xlsx `prompt` column (verified across
# 5 sample rows — see module docstring). {dish_name} and the four LLM-sourced blanks are the only
# variable slots; every other word is fixed, byte-for-byte, dish to dish.
PROMPT_TEMPLATE = (
    "Generate a high-quality professional food photograph of {dish_name}: {visual_description}. "
    "Served in a traditional {vessel_type}. The table surface is a clean warm-toned rustic wooden "
    "board with nothing else on it — no scattered spices, no loose herbs, no cloth, no glass, "
    "no items that are not part of the dish. Only the dish and its actual accompaniments. "
    "Photography style: 45-degree angle, soft natural window light from the left side, warm color "
    "temperature, shallow depth of field with a softly blurred background, appetizing steam rising "
    "gently. The colors should draw attention to {color_focal_point}. The image should look like "
    "premium editorial food photography — ultra sharp, high resolution, clean composition. "
    "Aspect ratio 16:9."
)


def clean_dish_name_for_prompt(raw_name: str) -> str:
    """Strips CSV article-title cruft down to a plain dish name for image-prompt use, matching
    the Founder-supplied reference (FooFoo_Dish_Image_Prompts_v2.xlsx): its dish_name column is
    always a clean name like "Butter Chicken" or "Tomato Rice", never a raw recipe-article title.

    The raw CSV RecipeName/TranslatedRecipeName are article titles, not dish names, and often
    carry both: a bilingual "<Devanagari> - <English>" pairing (e.g. "टमाटर पुलियोगरे रेसिपी -
    Spicy Tomato Rice (Recipe In Hindi)") and/or a trailing "Recipe" / "(Recipe In Hindi)" /
    "(Recipe)" suffix (e.g. "Masala Karela Recipe", "Maa Ki Dal Recipe"). Sent verbatim into an
    English-centric text-to-image model, both confuse it -- this is applied only to the string
    used inside the image prompt, never to the dish's canonical/database name.
    """
    import re

    name = raw_name.strip()
    if " - " in name:
        left, right = name.split(" - ", 1)
        if any(ord(ch) > 127 for ch in left):  # left side is non-Latin script -> keep the English side
            name = right
    name = re.sub(r"\s*\(recipe[^)]*\)\s*$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\s+recipe\s*$", "", name, flags=re.IGNORECASE)
    return name.strip() or raw_name.strip()


@dataclass
class PromptFields:
    category: str
    vessel_type: str
    visual_description: str
    color_focal_point: str
    source: str            # 'groq_api' | 'hf_api' | 'heuristic'
    model_name: str | None
    raw_response: dict | None


def assemble_prompt(dish_name: str, fields: PromptFields) -> str:
    """Server-owned assembly: the LLM never sees or produces the template text itself."""
    return PROMPT_TEMPLATE.format(
        dish_name=dish_name,
        visual_description=fields.visual_description,
        vessel_type=fields.vessel_type,
        color_focal_point=fields.color_focal_point,
    )


class ImagePromptGenerator:
    """Resolves the four fill-in fields for a dish, preferring Groq, then Hugging Face, then a
    deterministic heuristic — same pluggable-backend spirit as GroqAdapter in groq_adapter.py.
    """

    def __init__(self, groq_api_key: str | None = None, hf_api_key: str | None = None):
        self.groq_api_key = groq_api_key if groq_api_key is not None else os.environ.get("GROQ_API_KEY")
        self.hf_api_key = (
            hf_api_key
            if hf_api_key is not None
            else (os.environ.get("HF_API_KEY") or os.environ.get("HUGGINGFACE_API_KEY"))
        )

    def resolve_fields(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                        ingredients: list[str], force_heuristic: bool = False) -> PromptFields:
        if force_heuristic:
            return self._heuristic(dish_name, cuisine_raw, course_raw, ingredients)
        if self.groq_api_key:
            try:
                return self._call_groq(dish_name, cuisine_raw, course_raw, ingredients)
            except Exception as exc:  # pragma: no cover - network
                logger.warning("groq prompt-field call failed for %s: %s; falling back", dish_name, exc)
        if self.hf_api_key:
            try:
                return self._call_hf(dish_name, cuisine_raw, course_raw, ingredients)
            except Exception as exc:  # pragma: no cover - network
                logger.warning("hf prompt-field call failed for %s: %s; falling back to heuristic", dish_name, exc)
        return self._heuristic(dish_name, cuisine_raw, course_raw, ingredients)

    # -- heuristic fallback (no network, no key required) --------------------------------------
    def _heuristic(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                    ingredients: list[str]) -> PromptFields:
        category = " ".join(x for x in [cuisine_raw, course_raw] if x).strip() or "Indian dish"
        vessel_type = "serving bowl"
        top_ingredients = ", ".join(ingredients[:4]) if ingredients else "its traditional ingredients"
        visual_description = (
            f"{dish_name}, prepared with {top_ingredients}, presented with its typical color, "
            "texture and garnish, served with its usual accompaniment"
        )
        color_focal_point = "the dish's natural color and texture"
        return PromptFields(
            category=category, vessel_type=vessel_type, visual_description=visual_description,
            color_focal_point=color_focal_point, source="heuristic", model_name=None,
            raw_response={"method": "deterministic_heuristic", "note": "no GROQ_API_KEY/HF key configured"},
        )

    # -- Groq backend ----------------------------------------------------------------------------
    def _call_groq(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                    ingredients: list[str]) -> PromptFields:
        prompt = _fields_prompt(dish_name, cuisine_raw, course_raw, ingredients)
        payload = {
            "model": GROQ_MODEL,
            "messages": [
                {"role": "system", "content": "Return concise JSON only, no prose, no markdown fences."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 300,
        }
        req = urllib.request.Request(
            GROQ_API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.groq_api_key}", "Content-Type": "application/json",
                # see groq_adapter.py's same header for why this is required, not cosmetic.
                "User-Agent": "foofoo-dish-ingestion/1.0",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=25) as resp:  # pragma: no cover - network
            raw = json.loads(resp.read().decode("utf-8"))
        content = raw["choices"][0]["message"]["content"].strip()
        data = _parse_fields_json(content)
        return PromptFields(
            category=data["category"], vessel_type=data["vessel_type"],
            visual_description=data["visual_description"], color_focal_point=data["color_focal_point"],
            source="groq_api", model_name=GROQ_MODEL, raw_response=raw,
        )

    # -- Hugging Face Inference Providers router (alternate/fallback) ----------------------------
    def _call_hf(self, dish_name: str, cuisine_raw: str | None, course_raw: str | None,
                 ingredients: list[str]) -> PromptFields:
        prompt = _fields_prompt(dish_name, cuisine_raw, course_raw, ingredients)
        # OpenAI-compatible chat completions shape (router.huggingface.co), not the retired
        # raw text-generation `{"inputs": ...}` payload the old api-inference host accepted.
        payload = {
            "model": HF_MODEL,
            "messages": [
                {"role": "system", "content": "Return concise JSON only, no prose."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 300,
        }
        req = urllib.request.Request(
            HF_API_URL,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.hf_api_key}", "Content-Type": "application/json",
                "User-Agent": "foofoo-dish-ingestion/1.0",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:  # pragma: no cover - network
            raw = json.loads(resp.read().decode("utf-8"))
        content = raw["choices"][0]["message"]["content"].strip()
        data = _parse_fields_json(content)
        return PromptFields(
            category=data["category"], vessel_type=data["vessel_type"],
            visual_description=data["visual_description"], color_focal_point=data["color_focal_point"],
            source="hf_api", model_name=HF_MODEL, raw_response=raw,
        )


_FIELD_METHOD_INSTRUCTIONS = """You are filling in 4 blanks for a food-photography prompt template. Study this method,
learned from 867 professionally hand-written examples for this same product, before answering:

1. visual_description opens with the dish's PHYSICAL FORM + PRECISE COLOR + TEXTURE of its main
   component, derived from what the ingredients/cooking method actually produce -- never a vague
   "delicious" or "tasty". Turmeric/gram-flour dishes are yellow; tomato-butter gravies are
   orange-red; slow-cooked dals are dark brown; coconut-based preparations are pale
   white/cream; charred/tandoor items are red-orange or dark with visible char marks.
2. It then names ONE OR TWO visible cues that prove HOW it was cooked -- a glossy sheen, char
   marks, froth, a crisp/flaky edge, steam, spiraled/folded shape -- specific to this dish's real
   preparation, not generic.
3. It then names the REAL, traditional garnish and the REAL, traditional accompaniment for this
   exact dish by name (e.g. "buttered naan alongside", "raita alongside", "appam alongside") --
   never invent one; if you are not confident of a traditional accompaniment for this dish, omit
   that clause rather than guessing.
4. vessel_type is the culturally-authentic serving vessel for this dish's real regional cuisine
   (steel tumbler+dabarah for filter coffee, banana leaf for a South Indian meal, copper handi for
   a slow-cooked North Indian gravy, bamboo steamer for momos) -- default to "steel plate" or
   "steel bowl" only when no more specific vessel is traditional.
5. color_focal_point is 3-6 words naming the single most eye-catching visual element with its
   color, e.g. "the rich orange-red gravy and golden chicken pieces" or "the yellow spiraled
   rolls with sesame-coconut topping" -- not a generic restatement of the dish name.

Two real examples of the expected depth and style (for calibration only, not this dish):

Example 1 -- Dal Makhani (North Indian Dal, copper handi):
"Rich dark brown creamy lentil preparation made with whole black urad dal and rajma, slow-cooked
to a thick glossy consistency. A generous swirl of fresh cream on top with a pat of golden butter
melting. Garnished with coriander. Buttered naan alongside." focal: "the dark rich dal with cream
and butter contrast"

Example 2 -- Khandvi (Gujarati, steel plate):
"Thin yellow rolled gram flour sheets tightly rolled into small spirals, topped with tempering of
mustard seeds, sesame seeds, curry leaves, and grated coconut. Neat and uniform." focal: "the
yellow spiraled rolls with sesame-coconut topping"
"""


def _fields_prompt(dish_name: str, cuisine_raw: str | None, course_raw: str | None, ingredients: list[str]) -> str:
    ing_text = ", ".join(ingredients[:12]) if ingredients else "unknown"
    return (
        _FIELD_METHOD_INSTRUCTIONS +
        f"\nNow apply this method to: Indian dish '{dish_name}' (cuisine: '{cuisine_raw or 'unknown'}', "
        f"course: '{course_raw or 'unknown'}', key ingredients: {ing_text}).\n"
        "Respond with JSON only, exactly these keys: "
        '"category" (short cuisine/course label, e.g. "North Indian Gravy"), '
        '"vessel_type" (culturally-authentic traditional serving vessel per rule 4 above), '
        '"visual_description" (2-3 sentences following rules 1-3 above), '
        '"color_focal_point" (3-6 words per rule 5 above). '
        "No prose outside the JSON object."
    )


def _parse_fields_json(content: str) -> dict:
    # Strip accidental markdown fences some models add despite instructions.
    text = content.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
    data = json.loads(text)
    for key in ("category", "vessel_type", "visual_description", "color_focal_point"):
        if key not in data or not data[key]:
            raise ValueError(f"model response missing required field '{key}'")
    return data
