-- Migration: 105_seed_cuisines.sql
-- Title: public.cuisines — cuisine reference (groups denormalized)
-- Layer: ICD-1 content (WP-6D-gen v1.0)
-- Generated: 2026-07-14T03:41:23Z  by database/etl/generate_icd1_seeds.py (deterministic)
-- Transformation version: WP-6D-gen v1.0
-- Provenance (source workbook/sheet + checksum):
--   source: cuisines_v4.csv (sha256:a26b7d956e6f4147) — 65 rows
--   source: cuisine_groups_v4 2.csv — groups carried as denormalized cuisine_group text (Freeze Pack A)
-- Business rules applied:
--   - direct column map [TR-001/002]; parent_cuisine/state_origin blank -> NULL
--   - cuisine_group kept as text (no FK to a groups table) — Architecture Freeze §3 Pack A
--   - state_origin NOT FK'd to re_states (63 values incl. non-Indian) — Batch3 finding
-- Idempotency: INSERT ... ON CONFLICT DO NOTHING. Re-runnable. Paired _rollback.sql.
-- NOTE: supersedes the illustrative rows in 101/102 for the same tables (never edited in place).

BEGIN;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('punjabi','Punjabi','north_indian',NULL,'Punjab','Butter-heavy tandoor-centric. Dal makhani, butter chicken, sarson ka saag, chole bhature.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('kashmiri','Kashmiri','north_indian',NULL,'J&K','Wazwan tradition. Rogan josh, dum aloo, yakhni. Fennel, dry ginger, saffron.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('rajasthani','Rajasthani','north_indian',NULL,'Rajasthan','Desert cuisine. Dal baati churma, gatte ki sabzi, laal maas. Heavy ghee.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('himachali','Himachali','north_indian',NULL,'Himachal Pradesh','Mountain cuisine. Dham thali, madra, siddu. Yogurt-based gravies.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('uttarakhandi','Uttarakhandi','north_indian',NULL,'Uttarakhand','Garhwali + Kumaoni. Kafuli, chainsoo, bhatt ki churkani. Lentil-heavy.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('delhi','Delhi','north_indian',NULL,'Delhi','Melting pot. Chole bhature, paranthas, chaat, kebabs. Punjabi + Mughlai + UP influences.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('up','UP (General)','north_indian',NULL,'Uttar Pradesh','Broader UP home cooking. Tahiri, bedmi puri, baati chokha, kachori-sabzi.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('bihari','Bihari','north_indian',NULL,'Bihar','Litti chokha, sattu paratha, thekua, dal pitha. Sattu-centric, mustard oil.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('bundelkhandi','Bundelkhandi','north_indian',NULL,'Bundelkhand (MP/UP)','Rustic. Bafla, maheri, lapsi.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('sindhi','Sindhi','north_indian',NULL,'Sindh (diaspora)','Dal pakwan, sindhi kadhi, sai bhaji, koki. Gram flour heavy, tamarind-forward.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('tamil','Tamil','south_indian',NULL,'Tamil Nadu','Rice-centric, tamarind-forward. Sambar, rasam, poriyal, kootu.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('chettinad','Chettinad','south_indian','tamil','TN (Karaikudi)','Fiery merchant cuisine. Chettinad chicken, kuzhambu. Unique spices.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('kerala','Kerala','south_indian',NULL,'Kerala','Coconut-everything. Appam-stew, fish molee, avial, puttu-kadala, sadya.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('malabar','Malabar','south_indian','kerala','Kerala (North)','Muslim-influenced Kerala. Malabar biryani, pathiri.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('andhra','Andhra','south_indian',NULL,'Andhra Pradesh','Chilli-forward. Gongura, pesarattu, pulihora. India''s spiciest mainstream cuisine.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('telangana','Telangana','south_indian',NULL,'Telangana','Sakinalu, jonna rotte, sarva pindi. More millet-based than coastal Andhra.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('karnataka','Karnataka','south_indian',NULL,'Karnataka','Bisi bele bath, ragi mudde, jolada rotti. Diverse by sub-region.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('udupi','Udupi','south_indian','karnataka','Karnataka (Udupi)','Temple cuisine. Masala dosa, set dosa, sambar. Strictly vegetarian.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('mangalorean','Mangalorean','south_indian','karnataka','Karnataka (Mangalore)','Coastal. Kori rotti, fish gassi, neer dosa. Seafood-heavy.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('coorg','Coorg (Kodava)','south_indian','karnataka','Karnataka (Coorg)','Kodava tribal. Pandi curry (pork), bamboo shoot curry.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('bengali','Bengali','east_indian',NULL,'West Bengal','Fish and rice culture. Machher jhol, shorshe ilish, aloo posto, sandesh.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('odia','Odia','east_indian',NULL,'Odisha','Temple-influenced. Dalma, pakhala bhaat, chhena poda. Light, less oily.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('assamese','Assamese','east_indian',NULL,'Assam','Khar, masor tenga, aloo pitika. Minimal oil, fermented ingredients, bhut jolokia.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('jharkhandi','Jharkhandi','east_indian',NULL,'Jharkhand','Tribal/Adivasi. Dhuska, rugra. Forest ingredients, rustic.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('maharashtrian','Maharashtrian','west_indian',NULL,'Maharashtra','Vada pav, misal pav, puran poli, thalipeeth. Peanut + coconut base.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('malvani','Malvani','west_indian','maharashtrian','Maharashtra (Konkan)','Coastal. Malvani fish curry, sol kadhi. Coconut-heavy, fiery.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('kolhapuri','Kolhapuri','west_indian','maharashtrian','Maharashtra (Kolhapur)','Extreme heat. Tambda/pandhra rassa. Special Kolhapuri masala.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('vidarbha','Vidarbha','west_indian','maharashtrian','Maharashtra (Vidarbha)','Saoji cuisine — extremely spicy. More Central Indian influence.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('gujarati','Gujarati','west_indian',NULL,'Gujarat','Sweet-in-everything. Dhokla, thepla, undhiyu, khandvi. Sugar/jaggery in curries.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('kutchi','Kutchi','west_indian','gujarati','Gujarat (Kutch)','Desert Gujarati. Dabeli, bajri rotla. Millet-heavy.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('goan','Goan','west_indian',NULL,'Goa','Portuguese-influenced. Vindaloo, xacuti, bebinca. Vinegar, kokum, coconut.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('konkani','Konkani','west_indian',NULL,'Konkan Coast','Broader coastal. Sol kadhi, amboli. Coconut + kokum + seafood.','tier_2',false,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('parsi','Parsi','west_indian',NULL,'Mumbai/Gujarat','Zoroastrian community. Dhansak, patra ni machhi, salli boti. Sweet-sour-spicy.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('madhya_pradesh','Madhya Pradesh','central_indian',NULL,'Madhya Pradesh','Bhopali + Indori + Malwa. Varies widely by city.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('indori','Indori','central_indian','madhya_pradesh','MP (Indore)','Street food powerhouse. Poha-jalebi, bhutte ka kees. Snacking capital.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('chhattisgarhi','Chhattisgarhi','central_indian',NULL,'Chhattisgarh','Rice-and-lentil tribal. Fara, muthiya, bore baasi. Simple, minimal spice.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('naga','Naga','northeast_indian',NULL,'Nagaland','Fermented, smoked, fiery. Smoked pork, axone, raja mirchi chutney.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('manipuri','Manipuri','northeast_indian',NULL,'Manipur','Eromba, singju, kangshoi. Fermented fish, light, soup-heavy.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('mizo','Mizo','northeast_indian',NULL,'Mizoram','Bai, sawhchiar. Boiled/steamed, closest to Southeast Asian in India.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('sikkimese','Sikkimese','northeast_indian',NULL,'Sikkim','Tibetan-Nepali influenced. Momos, thukpa, gundruk, sel roti.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('meghalayan','Meghalayan','northeast_indian',NULL,'Meghalaya','Jadoh, tungrymbai. Khasi + Garo tribal. Black sesame.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('arunachali','Arunachali','northeast_indian',NULL,'Arunachal Pradesh','Thukpa, pika pila. Minimal spice, smoked meats.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('tripuri','Tripuri','northeast_indian',NULL,'Tripura','Mui borok, berma. Bengali-influenced with tribal preparations.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('mughlai','Mughlai','mughlai_nawabi',NULL,'Delhi/UP','Rich Mughal court cuisine. Biryanis, kormas, kebabs, nihari. Cream, nuts, saffron.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('awadhi','Awadhi','mughlai_nawabi','mughlai','Lucknow/UP','Refined Nawabi. Dum cooking, galouti kebab, Lucknowi biryani.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('hyderabadi','Hyderabadi','mughlai_nawabi',NULL,'Hyderabad','Nizam court cuisine. Hyderabadi biryani, haleem, mirchi ka salan.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('street_food_generic','Street Food (Pan-Indian)','street_food',NULL,'Pan-India','Chaat, vada pav, pav bhaji, pani puri, bhel puri, kathi roll.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('indian_bakery','Indian Bakery','street_food',NULL,'Pan-India','Pav, khari biscuit, maska bun, nankhatai, plum cake.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('indo_chinese','Indo-Chinese','chinese_asian',NULL,'Pan-India (Kolkata origin)','Hakka noodles, manchurian, chilli chicken/paneer, fried rice.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('chinese_authentic','Chinese (Authentic)','chinese_asian',NULL,'China','Dim sum, mapo tofu, Sichuan. Growing in metros.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('indian_tibetan','Indian-Tibetan','chinese_asian',NULL,'Hill stations/NE','Momos (Indian style), thukpa, tingmo. Tibetan base + Indian spices.','tier_2',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('continental','Continental','continental',NULL,'Europe (generic)','Indian catch-all for Western food. Grilled chicken, soups, salads, sandwiches.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('italian','Italian','italian',NULL,'Italy','Pasta, pizza, risotto. Widely eaten in urban India.','tier_1',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('american','American','american',NULL,'USA','Burgers, fries, mac and cheese, BBQ, pancakes.','tier_2',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('mediterranean','Mediterranean','mediterranean',NULL,'Mediterranean region','Grain bowls, grilled meats, olive oil based. Health-food trend.','tier_3',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('anglo_indian','Anglo-Indian','anglo_indian',NULL,'Pan-India','Mulligatawny soup, railway mutton curry, jhal frezi. British-Indian colonial fusion.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('thai','Thai','thai',NULL,'Thailand','Pad thai, green/red curry, tom yum. Coconut base familiar to South Indians.','tier_2',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('japanese','Japanese','japanese',NULL,'Japan','Sushi, ramen, tempura, teriyaki. Niche but growing.','tier_3',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('korean','Korean','korean',NULL,'South Korea','Kimchi, bibimbap, Korean fried chicken. K-wave driving adoption in Gen Z.','tier_2',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('middle_eastern_generic','Middle Eastern','middle_eastern',NULL,'Middle East','Hummus, falafel, shawarma, kebab platters.','tier_2',true,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('lebanese','Lebanese','middle_eastern','middle_eastern_generic','Lebanon','Tabbouleh, manoushe, kibbeh. Often listed separately on Indian menus.','tier_3',false,false) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('bhutanese','Bhutanese','bhutanese',NULL,'Bhutan','Ema datshi, phaksha paa. Chilli + cheese focused.','tier_3',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('burmese','Burmese','burmese',NULL,'Burma','Mohinga, khow suey, tea leaf salad. SE Asian + Indian fusion.','tier_3',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('mexican','Mexican','mexican',NULL,'Mexico','Tacos, burritos, quesadillas. Corn + beans + chilli.','tier_3',true,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.cuisines (name,display_name,cuisine_group,parent_cuisine,state_origin,description,tier,is_user_facing,is_active) VALUES ('vietnamese','Vietnamese','vietnamese',NULL,'Vietnam','Pho, banh mi, spring rolls. Fresh herbs + light broths.','tier_3',true,true) ON CONFLICT (name) DO NOTHING;
COMMIT;
