-- Migration: 109_seed_dish_combos.sql
-- Title: public.dish_combos + dish_combo_items
-- Layer: ICD-1 content (WP-6D-gen v1.0)
-- Generated: 2026-07-14T03:41:23Z  by database/etl/generate_icd1_seeds.py (deterministic)
-- Transformation version: WP-6D-gen v1.0
-- Provenance (source workbook/sheet + checksum):
--   source: dish_combos_v2_20260520.csv (35) + dish_combo_items_v2_20260520.csv (74)
-- Business rules applied:
--   - combo_type validated against CHECK {inseparable,base_with_sides,thali}
--   - meal_occasion = split(meal_types, ',') -> text[]
--   - item role -> 3-value CHECK; component_type -> 8-value CHECK (migration 025)
--   - combo item dish_id resolved from public.dishes(name); unresolved items skipped (ICD-1)
-- Idempotency: INSERT ... ON CONFLICT DO NOTHING. Re-runnable. Paired _rollback.sql.
-- NOTE: supersedes the illustrative rows in 101/102 for the same tables (never edited in place).

BEGIN;
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Chole Bhature','inseparable',ARRAY['breakfast', 'lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Rajma Chawal','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Dal Chawal','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Idli Sambar','base_with_sides',ARRAY['breakfast', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Masala Dosa Set','base_with_sides',ARRAY['breakfast', 'lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Dosa Sambar','base_with_sides',ARRAY['breakfast', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Medu Vada Sambar','base_with_sides',ARRAY['breakfast', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Dal Baati Churma','inseparable',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Sarson Ka Saag Makki Ki Roti','inseparable',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Poha Jalebi','inseparable',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Chole Kulche','base_with_sides',ARRAY['breakfast', 'lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Puri Aloo','base_with_sides',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Bedmi Puri Aloo','inseparable',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Kerala Rice Meals','thali',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Hyderabadi Biryani Set','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Puttu Kadala','inseparable',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Paratha Curd Pickle','base_with_sides',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Matar Kulcha','inseparable',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Chole Bhature (Delhi)','inseparable',ARRAY['breakfast', 'lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Nihari Kulcha','inseparable',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Pav Bhaji Set','inseparable',ARRAY['lunch', 'dinner', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Thali Meals (South Indian)','thali',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Sadya Thali','thali',ARRAY['lunch']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Dahi Vada Set','base_with_sides',ARRAY['snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Chole Tikki Set','base_with_sides',ARRAY['snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Roti Sabzi','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Uttapam Set','base_with_sides',ARRAY['breakfast', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Vada Sambar','base_with_sides',ARRAY['breakfast', 'snacks']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Keema Pav','inseparable',ARRAY['breakfast', 'lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Biryani Raita','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Chholar Dal with Luchi','base_with_sides',ARRAY['breakfast', 'lunch']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Daal Bafla','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Pithla Bhakri','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Dal Pakwan','base_with_sides',ARRAY['breakfast']::text[],true);
INSERT INTO public.dish_combos (combo_name,combo_type,meal_occasion,is_active) VALUES ('Zunka Bhakri','base_with_sides',ARRAY['lunch', 'dinner']::text[],true);
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Bhature' AND d.name='Chole' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Bhature' AND d.name='Bhatura' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Rajma Chawal' AND d.name='Rajma' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'carb_base', true, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Rajma Chawal' AND d.name='Jeera Rice' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'carb_base', false, true, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Rajma Chawal' AND d.name='Phulka' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, true, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Chawal' AND d.name='Dal Tadka' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'carb_base', true, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Chawal' AND d.name='Jeera Rice' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'carb_base', false, true, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Chawal' AND d.name='Phulka' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Idli Sambar' AND d.name='Idli' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Idli Sambar' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'condiment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Idli Sambar' AND d.name='Coconut Chutney' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Masala Dosa Set' AND d.name='Masala Dosa' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Masala Dosa Set' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'condiment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Masala Dosa Set' AND d.name='Coconut Chutney' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dosa Sambar' AND d.name='Plain Dosa' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dosa Sambar' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'condiment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dosa Sambar' AND d.name='Coconut Chutney' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Medu Vada Sambar' AND d.name='Medu Vada' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Medu Vada Sambar' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'condiment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Medu Vada Sambar' AND d.name='Coconut Chutney' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Baati Churma' AND d.name='Dal Baati' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'dessert', false, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Baati Churma' AND d.name='Churma' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Sarson Ka Saag Makki Ki Roti' AND d.name='Sarson Ka Saag' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Sarson Ka Saag Makki Ki Roti' AND d.name='Makki Ki Roti' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Poha Jalebi' AND d.name='Indori Poha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'dessert', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Poha Jalebi' AND d.name='Jalebi' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Kulche' AND d.name='Chole' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Kulche' AND d.name='Kulcha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Kulche' AND d.name='Naan' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Puri Aloo' AND d.name='Puri' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Puri Aloo' AND d.name='Aloo Sabzi (Delhi style)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Bedmi Puri Aloo' AND d.name='Bedmi Puri' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Bedmi Puri Aloo' AND d.name='Aloo Sabzi (Delhi style)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'carb_base', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Kerala Rice Meals' AND d.name='Steamed Rice' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Kerala Rice Meals' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Kerala Rice Meals' AND d.name='Rasam' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 4 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Kerala Rice Meals' AND d.name='Parippu Curry' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', false, false, 5 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Kerala Rice Meals' AND d.name='Avial (Kerala)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, true, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Hyderabadi Biryani Set' AND d.name='Hyderabadi Chicken Biryani' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Hyderabadi Biryani Set' AND d.name='Hyderabadi Mutton Biryani' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Hyderabadi Biryani Set' AND d.name='Mirchi Ka Salan' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Puttu Kadala' AND d.name='Puttu' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Puttu Kadala' AND d.name='Kadala Curry' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, true, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Paratha Curd Pickle' AND d.name='Aloo Paratha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Paratha Curd Pickle' AND d.name='Gobhi Paratha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', false, true, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Paratha Curd Pickle' AND d.name='Paneer Paratha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'beverage', false, false, 4 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Paratha Curd Pickle' AND d.name='Lassi (Salted)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Matar Kulcha' AND d.name='Matar Kulcha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Nihari Kulcha' AND d.name='Nahari Kulcha' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Pav Bhaji Set' AND d.name='Pav Bhaji (Delhi style)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Thali Meals (South Indian)' AND d.name='Thali Meals (South Indian)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Sadya Thali' AND d.name='Sadya Thali' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dahi Vada Set' AND d.name='Dahi Bhalla' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chole Tikki Set' AND d.name='Chole Tikki' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', true, true, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Roti Sabzi' AND d.name='Phulka' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Roti Sabzi' AND d.name='Aloo Gobhi' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Uttapam Set' AND d.name='Uttapam' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Uttapam Set' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'condiment', true, false, 3 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Uttapam Set' AND d.name='Coconut Chutney' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Vada Sambar' AND d.name='Medu Vada' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'accompaniment', 'accompaniment', true, false, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Vada Sambar' AND d.name='Sambar' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'standalone', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Keema Pav' AND d.name='Keema Pav' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, true, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Biryani Raita' AND d.name='Biryani (Mughlai Chicken)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Biryani Raita' AND d.name='Lucknowi Biryani' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chholar Dal with Luchi' AND d.name='Chholar Dal' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Chholar Dal with Luchi' AND d.name='Luchi' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Daal Bafla' AND d.name='Dal (Mixed)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Daal Bafla' AND d.name='Bafla' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Pithla Bhakri' AND d.name='Pithla' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Pithla Bhakri' AND d.name='Bhakri' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Pakwan' AND d.name='Dal (Sindhi)' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Dal Pakwan' AND d.name='Pakwan' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'primary', 'primary', true, false, 1 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Zunka Bhakri' AND d.name='Zunka' ON CONFLICT DO NOTHING;
INSERT INTO public.dish_combo_items (combo_id,dish_id,role,component_type,is_default,is_swappable,sort_order) SELECT dc.id, d.id, 'side', 'bread', false, true, 2 FROM public.dish_combos dc, public.dishes d WHERE dc.combo_name='Zunka Bhakri' AND d.name='Bhakri' ON CONFLICT DO NOTHING;
COMMIT;
