import { useState } from "react";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useI18n } from "@/i18n";
import { FButton, ProgressBar, palette } from "@/ui/foofoo";
const FOOD = require("../assets/images/poha-idli-fruit.png");
const steps = { en: ["Rinse the poha gently and rest for 5 minutes.", "Warm oil; add mustard, curry leaves and peanuts.", "Fold in poha, turmeric and salt. Finish with lemon."], hi: ["पोहा हल्के हाथ से धोकर 5 मिनट रखें।", "तेल गरम करके राई, करी पत्ता और मूंगफली डालें।", "पोहा, हल्दी और नमक मिलाएँ। नींबू डालकर पूरा करें।"] };
export default function Cooking() {
  const { t, locale } = useI18n(); const [step, setStep] = useState(0); const [running, setRunning] = useState(false); const instructions = steps[locale];
  return <View style={s.screen}><View style={s.header}><Pressable style={s.headerTouch} onPress={() => router.back()}><Text style={s.close}>×</Text></Pressable><Text style={s.title}>{t("cookingTitle")}</Text><Pressable style={s.pause} onPress={() => setRunning(false)}><Text style={s.pauseText}>Ⅱ {t("pause")}</Text></Pressable></View><Image source={FOOD} style={s.hero} /><View style={s.body}><View style={s.progressHead}><Text style={s.progressText}>{step + 1} / {instructions.length}</Text><Text style={s.progressText}>{Math.round(((step + 1) / instructions.length) * 100)}%</Text></View><ProgressBar progress={(step + 1) / instructions.length} /><Text style={s.kicker}>{t("stepLabel")} {step + 1}</Text><Text style={s.step}>{instructions[step]}</Text><View style={s.hints}><View style={s.hint}><Text style={s.hintIcon}>🥣</Text><View><Text style={s.hintLabel}>{t("toolHint")}</Text><Text style={s.hintValue}>{step === 0 ? "Colander" : "Kadai"}</Text></View></View><View style={s.hint}><Text style={s.hintIcon}>🌿</Text><View><Text style={s.hintLabel}>{t("ingredientHint")}</Text><Text style={s.hintValue}>{step === 0 ? "Poha + water" : "Curry leaves"}</Text></View></View></View><Pressable style={s.timer} onPress={() => setRunning(!running)}><Text style={s.timerIcon}>◷</Text><View><Text style={s.timerTime}>05:00</Text><Text style={s.timerText}>{running ? t("timerRunning") : t("startTimer")}</Text></View></Pressable><View style={s.actions}><FButton kind="secondary" label={t("previous")} disabled={step === 0} onPress={() => setStep(Math.max(0, step - 1))} style={{ flex: 1 }} /><FButton label={step === instructions.length - 1 ? t("finish") : t("nextStep")} onPress={() => step === instructions.length - 1 ? router.back() : setStep(step + 1)} style={{ flex: 1 }} /></View></View></View>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, header: { height: 64, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTouch: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, close: { fontSize: 30 }, title: { fontSize: 17, fontWeight: "800" }, pause: { minHeight: 38, paddingHorizontal: 10, borderRadius: 12, backgroundColor: palette.purpleSoft, justifyContent: "center" }, pauseText: { color: palette.purple, fontSize: 10, fontWeight: "700" }, hero: { width: "100%", height: 250 }, body: { padding: 20, gap: 16 }, progressHead: { flexDirection: "row", justifyContent: "space-between" }, progressText: { fontSize: 10, color: palette.muted }, kicker: { fontSize: 11, color: palette.purple, fontWeight: "800", letterSpacing: 1 }, step: { fontSize: 23, lineHeight: 31, fontWeight: "700", color: palette.ink }, hints: { flexDirection: "row", gap: 9 }, hint: { flex: 1, flexDirection: "row", gap: 8, alignItems: "center", padding: 10, borderRadius: 13, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.line }, hintIcon: { fontSize: 20 }, hintLabel: { fontSize: 8, color: palette.muted }, hintValue: { fontSize: 10, fontWeight: "700", color: palette.ink, marginTop: 2 }, timer: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 13, padding: 14, borderRadius: 15, backgroundColor: palette.purpleSoft }, timerIcon: { fontSize: 30, color: palette.purple }, timerTime: { fontSize: 20, fontWeight: "800" }, timerText: { fontSize: 10, color: palette.muted }, actions: { flexDirection: "row", gap: 10, marginTop: 4 } });
