import { useState } from "react";
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useI18n } from "@/i18n";
import { FButton, FChip, FInput, Sheet, palette } from "@/ui/foofoo";

const groups = [{ key: "vegetables" as const, items: [["🍅", "Tomato", "500 g"], ["🧅", "Onion", "1 kg"], ["🌿", "Coriander Leaves", "1 bunch"]] }, { key: "dairy" as const, items: [["🥛", "Milk", "1 L"]] }, { key: "grainsPulses" as const, items: [["🫙", "Toor Dal", "500 g"], ["🫙", "Basmati Rice", "1 kg"]] }];
export default function Grocery() {
  const { t } = useI18n(); const [checked, setChecked] = useState<string[]>(["Milk"]); const [filter, setFilter] = useState<"all" | "missing" | "have">("all"); const [showAdd, setShowAdd] = useState(false); const [draft, setDraft] = useState("");
  return <View style={s.screen}><ScrollView contentContainerStyle={s.page}><View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>{t("grocery")}</Text><Pressable onPress={() => Share.share({ message: "FooFoo grocery list" })}><Text style={s.share}>↗</Text></Pressable></View><View style={s.filters}><FChip label={`${t("all")} (12)`} selected={filter === "all"} onPress={() => setFilter("all")} /><FChip label={`${t("missing")} (6)`} selected={filter === "missing"} onPress={() => setFilter("missing")} /><FChip label={`${t("have")} (7)`} selected={filter === "have"} onPress={() => setFilter("have")} /></View>{groups.map(({ key, items }) => <View key={key} style={s.groupCard}><Text style={s.group}>{t(key)}</Text>{items.filter(([, name]) => filter === "all" || (filter === "have" ? checked.includes(name) : !checked.includes(name))).map(([icon, name, amount]) => <Pressable key={name} style={s.row} onPress={() => setChecked((old) => old.includes(name) ? old.filter((v) => v !== name) : [...old, name])}><View style={s.iconWrap}><Text style={s.icon}>{icon}</Text></View><View style={s.body}><Text style={[s.name, checked.includes(name) && s.done]}>{name}</Text><Text style={s.amount}>{amount}</Text></View><View style={[s.box, checked.includes(name) && s.boxOn]}><Text style={s.tick}>{checked.includes(name) ? "✓" : ""}</Text></View></Pressable>)}</View>)}<FButton kind="secondary" label={t("addGrocery")} onPress={() => setShowAdd(true)} /><FButton label={`↗ ${t("shareList")}`} onPress={() => Share.share({ message: "FooFoo grocery list" })} /></ScrollView><Sheet visible={showAdd} onClose={() => setShowAdd(false)}><Text style={s.sheetTitle}>{t("addGrocery")}</Text><FInput autoFocus value={draft} onChangeText={setDraft} placeholder="Tomato, 500 g" /><FButton label={t("addItem")} disabled={!draft.trim()} onPress={() => { setDraft(""); setShowAdd(false); }} /></Sheet></View>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, page: { padding: 18, paddingBottom: 40, gap: 12 }, header: { height: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { fontSize: 34 }, title: { fontSize: 18, fontWeight: "800" }, share: { color: palette.purple, fontSize: 20 }, filters: { flexDirection: "row", gap: 8 }, groupCard: { backgroundColor: palette.surface, borderRadius: 16, borderWidth: 1, borderColor: palette.line, paddingHorizontal: 13, paddingTop: 12 }, group: { fontWeight: "800", color: palette.ink, marginBottom: 4 }, row: { height: 64, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: palette.line }, iconWrap: { width: 38, height: 38, borderRadius: 11, backgroundColor: palette.beige, alignItems: "center", justifyContent: "center", marginRight: 10 }, icon: { fontSize: 20 }, body: { flex: 1 }, name: { fontWeight: "700" }, done: { textDecorationLine: "line-through", color: palette.muted }, amount: { fontSize: 11, color: palette.muted, marginTop: 2 }, box: { width: 22, height: 22, borderRadius: 6, borderWidth: 1.5, borderColor: palette.muted, alignItems: "center", justifyContent: "center" }, boxOn: { backgroundColor: palette.green, borderColor: palette.green }, tick: { color: "white", fontSize: 12, fontWeight: "800" }, sheetTitle: { fontSize: 20, fontWeight: "800", marginBottom: 12 } });
