import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useI18n } from "@/i18n";
import { FButton, Toast, palette } from "@/ui/foofoo";
const FOOD = require("../assets/images/poha-idli-fruit.png");
export default function MealDetail(){const {meal="Poha, Idli & Fruit Bowl"}=useLocalSearchParams<{meal:string}>();const {t}=useI18n();const [tab,setTab]=useState("about");const [saved,setSaved]=useState(false);return <View style={s.screen}><ScrollView contentContainerStyle={s.page}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.headerTitle}>{t("mealDetail")}</Text><Text>↗</Text></View><View style={s.card}><View style={s.mealHead}><Image source={FOOD} style={s.thumb}/><View><Text style={s.slot}>{t("breakfast")}</Text><Text style={s.meal}>{meal}</Text><Text style={s.caption}>Light · Balanced · Quick</Text></View></View><Image source={FOOD} style={s.hero}/><View style={s.metrics}><Metric icon="◷" value={t("mins")} label="Prep & Cook"/><Metric icon="♨" value={t("easy")} label="Difficulty"/><Metric icon="♨" value={t("calories")} label="Calories"/></View><View style={s.tabs}>{(["about","nutrition","ingredients","steps"] as const).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabActive]}><Text style={[s.tabText,tab===x&&s.tabTextActive]}>{t(x)}</Text></Pressable>)}</View><View style={s.copy}><Text style={s.body}>{tab==="ingredients"?"Poha · idli rice · seasonal fruit · peanuts · curry leaves":tab==="steps"?"1. Rinse and soften poha.  2. Temper spices.  3. Fold together and garnish.":"A perfect blend of carbs, protein and micronutrients to kickstart your day."}</Text><Text style={s.why}>{t("whyGreat")}</Text>{["Light on stomach","Rich in iron & fibre","Keeps you full for longer"].map(x=><Text key={x} style={s.benefit}>✓  {x}</Text>)}</View><View style={s.actions}><Pressable onPress={()=>setSaved(!saved)} style={s.save}><Text style={{color:palette.red}}>{saved?"♥":"♡"} 120</Text></Pressable><FButton label={t("selectThis")} style={{flex:1}} onPress={()=>setSaved(true)}/><Pressable style={s.more}><Text>•••</Text></Pressable></View></View><View style={s.ai}><Text style={s.aiTitle}>✦  AI Suggestion</Text><Text style={s.aiText}>Based on your preferences and what’s in your pantry, this is a strong fit.</Text></View><FButton kind="secondary" label={t("cookingMode")} onPress={()=>router.push("/cooking")}/></ScrollView><Toast visible={saved} text="Saved to Tuesday’s breakfast"/></View>}
function Metric({icon,value,label}:{icon:string;value:string;label:string}){return <View style={s.metric}><Text>{icon}</Text><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg},page:{padding:16,paddingBottom:50,gap:16},header:{height:46,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:34},headerTitle:{fontSize:17,fontWeight:"800"},card:{backgroundColor:"white",borderRadius:20,borderWidth:1,borderColor:palette.line,overflow:"hidden"},mealHead:{flexDirection:"row",gap:10,padding:14,alignItems:"center"},thumb:{width:46,height:46,borderRadius:23},slot:{fontSize:11,color:palette.muted},meal:{fontWeight:"800",fontSize:16,color:palette.ink},caption:{fontSize:11,color:palette.muted},hero:{width:"100%",height:245},metrics:{flexDirection:"row",borderBottomWidth:1,borderBottomColor:palette.line},metric:{flex:1,alignItems:"center",paddingVertical:14,borderRightWidth:1,borderRightColor:palette.line},metricValue:{fontSize:12,fontWeight:"800",marginTop:4},metricLabel:{fontSize:9,color:palette.muted,marginTop:3},tabs:{flexDirection:"row",paddingHorizontal:10,borderBottomWidth:1,borderBottomColor:palette.line},tab:{flex:1,paddingVertical:13,alignItems:"center"},tabActive:{borderBottomWidth:2,borderBottomColor:palette.purple},tabText:{fontSize:10,color:palette.muted},tabTextActive:{color:palette.purple,fontWeight:"800"},copy:{padding:16,gap:10},body:{fontSize:13,lineHeight:19,color:palette.ink},why:{fontWeight:"800",marginTop:7},benefit:{fontSize:12,color:palette.ink},actions:{flexDirection:"row",padding:12,gap:8,alignItems:"center"},save:{height:50,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:palette.line,alignItems:"center",justifyContent:"center"},more:{height:50,width:45,borderRadius:12,borderWidth:1,borderColor:palette.line,alignItems:"center",justifyContent:"center"},ai:{padding:17,borderRadius:16,backgroundColor:"#FCF0F7",gap:8},aiTitle:{color:palette.purple,fontWeight:"800"},aiText:{fontSize:12,lineHeight:18,color:palette.muted}});
