import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useI18n, type MessageKey } from "@/i18n";
import { FChip, FInput, palette } from "@/ui/foofoo";
const FOOD = require("../../assets/images/poha-idli-fruit.png");
const ideas = ["Moong Dal Cheela", "Lauki Kofta Curry", "Veg Clear Soup"];
export default function Chat() {
  const { t } = useI18n(); const [text, setText] = useState(""); const [sent, setSent] = useState<string[]>([]); const prompts: MessageKey[] = ["chatPromptOne", "chatPromptTwo", "chatPromptThree"];
  const send = (message = text.trim()) => { if (!message) return; setSent((old) => [...old, message]); setText(""); };
  return <View style={s.screen}><View style={s.header}><Text style={s.spark}>✦</Text><View><Text style={s.title}>{t("aiTitle")}</Text><Text style={s.online}>● {t("strongFit")}</Text></View><Text style={s.refresh}>↻</Text></View><ScrollView contentContainerStyle={s.body}><View style={s.promptBlock}><Text style={s.promptTitle}>{t("quickPrompts")}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.prompts}>{prompts.map((key) => <FChip key={key} label={t(key)} onPress={() => send(t(key))} />)}</ScrollView></View><View style={s.user}><Text style={s.message}>{t("aiHello")}</Text></View><View style={s.bot}><Text style={s.message}>{t("aiReply")}</Text></View>{ideas.map((name, i) => <Pressable key={name} style={({ pressed }) => [s.idea, pressed && s.ideaPressed]}><Image source={FOOD} style={s.image} /><View style={s.ideaCopy}><Text style={s.ideaName}>{name}</Text><Text style={s.meta}>{i === 0 ? t("highProtein") : i === 1 ? t("lightTasty") : t("lowCalorie")}</Text></View><Text style={s.chev}>›</Text></Pressable>)}{sent.map((message, index) => <View key={`${message}-${index}`} style={s.user}><Text style={s.message}>{message}</Text></View>)}</ScrollView><View style={s.compose}><FInput style={{ flex: 1 }} placeholder={t("typeMessage")} value={text} onChangeText={setText} onSubmitEditing={() => send()} /><Pressable style={({ pressed }) => [s.send, pressed && s.ideaPressed]} onPress={() => send()}><Text style={s.sendText}>›</Text></Pressable></View></View>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, header: { height: 66, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: palette.line, backgroundColor: palette.backgroundAlt }, spark: { color: palette.purple, fontSize: 21 }, title: { fontSize: 17, fontWeight: "800", color: palette.ink }, online: { fontSize: 8, color: palette.green, textAlign: "center", marginTop: 1 }, refresh: { fontSize: 19, color: palette.muted }, body: { padding: 18, paddingBottom: 105, gap: 12 }, promptBlock: { gap: 8, marginBottom: 4 }, promptTitle: { fontSize: 11, color: palette.muted, fontWeight: "700" }, prompts: { gap: 7 }, user: { alignSelf: "flex-end", maxWidth: "82%", backgroundColor: palette.purpleSoft, padding: 13, borderRadius: 17, borderBottomRightRadius: 4 }, bot: { alignSelf: "flex-start", maxWidth: "88%", backgroundColor: palette.surface, padding: 13, borderRadius: 17, borderBottomLeftRadius: 4, borderWidth: 1, borderColor: palette.line }, message: { color: palette.ink, lineHeight: 19 }, idea: { flexDirection: "row", alignItems: "center", gap: 12, padding: 10, backgroundColor: palette.surface, borderRadius: 15, borderWidth: 1, borderColor: palette.line }, ideaPressed: { opacity: .75, transform: [{ scale: .99 }] }, image: { width: 58, height: 58, borderRadius: 11 }, ideaCopy: { flex: 1 }, ideaName: { fontWeight: "700", color: palette.ink }, meta: { fontSize: 10, color: palette.green, marginTop: 4 }, chev: { fontSize: 24, color: palette.purple }, compose: { position: "absolute", bottom: 0, left: 0, right: 0, flexDirection: "row", gap: 8, padding: 12, backgroundColor: palette.backgroundAlt, borderTopWidth: 1, borderTopColor: palette.line }, send: { width: 48, height: 48, borderRadius: 24, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" }, sendText: { color: "white", fontSize: 29 } });
