import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useI18n, type MessageKey } from "@/i18n";
import { FButton, FChip, FInput, Sheet, palette } from "@/ui/foofoo";

const items = [["🫙", "Toor Dal", "750 g", "low"], ["🫙", "Basmati Rice", "2 kg", "ok"], ["🫙", "Moong Dal", "500 g", "ok"], ["🫙", "Besan", "1 kg", "low"], ["🌶️", "Red Chilli Powder", "100 g", "expiry"], ["🟡", "Turmeric Powder", "200 g", "ok"]] as const;
export default function Pantry() {
  const { t } = useI18n(); const [filter, setFilter] = useState<MessageKey>("all"); const [showAdd, setShowAdd] = useState(false); const [draft, setDraft] = useState("");
  const status = (value: string) => value === "low" ? t("low") : value === "expiry" ? t("expirySoon") : t("inStock");
  return <View style={s.screen}><ScrollView contentContainerStyle={s.page}><View style={s.header}><View><Text style={s.title}>{t("pantryTitle")}</Text><Text style={s.subtitle}>42 {t("inStock")} · 2 {t("low")}</Text></View><Pressable onPress={() => router.push("/grocery")}><Text style={s.grocery}>{t("grocery")} ›</Text></Pressable></View><FInput placeholder={`⌕  ${t("searchPantry")}`} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{(["all", "grains", "pulses", "spices", "others"] as MessageKey[]).map((key) => <FChip key={key} label={t(key)} selected={filter === key} onPress={() => setFilter(key)} />)}</ScrollView><View style={s.list}>{items.map(([icon, name, amount, itemStatus]) => <View key={name} style={s.row}><View style={s.jarWrap}><Text style={s.jar}>{icon}</Text></View><View style={s.body}><Text style={s.name}>{name}</Text><Text style={s.amount}>{amount}</Text></View><Text style={[s.badge, itemStatus === "low" ? s.low : itemStatus === "expiry" ? s.expiry : s.ok]}>{status(itemStatus)}</Text></View>)}</View><FButton label={t("quickAdd")} onPress={() => setShowAdd(true)} /></ScrollView><Sheet visible={showAdd} onClose={() => setShowAdd(false)}><Text style={s.sheetTitle}>{t("quickAdd")}</Text><Text style={s.sheetHint}>{t("searchPantry")}</Text><FInput autoFocus value={draft} onChangeText={setDraft} placeholder="e.g. Masoor dal, 500 g" /><FButton label={t("addItem")} disabled={!draft.trim()} onPress={() => { setDraft(""); setShowAdd(false); }} /></Sheet></View>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, page: { padding: 18, paddingBottom: 110, gap: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 }, title: { fontSize: 22, fontWeight: "800", color: palette.ink }, subtitle: { fontSize: 10, color: palette.muted, marginTop: 3 }, grocery: { color: palette.purple, fontWeight: "700", fontSize: 12 }, chips: { gap: 7 }, list: { backgroundColor: palette.surface, borderRadius: 18, paddingHorizontal: 14, borderWidth: 1, borderColor: palette.line }, row: { flexDirection: "row", alignItems: "center", minHeight: 68, borderBottomWidth: 1, borderBottomColor: palette.line }, jarWrap: { width: 38, height: 38, borderRadius: 12, backgroundColor: palette.beige, alignItems: "center", justifyContent: "center", marginRight: 10 }, jar: { fontSize: 20 }, body: { flex: 1 }, name: { fontWeight: "700", color: palette.ink }, amount: { fontSize: 11, color: palette.muted, marginTop: 2 }, badge: { fontSize: 9, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 6, overflow: "hidden", maxWidth: 82 }, low: { color: palette.red, backgroundColor: "#FFF0F2" }, expiry: { color: "#9B6700", backgroundColor: "#FFF5DB" }, ok: { color: "#16844B", backgroundColor: "#EAF8F0" }, sheetTitle: { fontSize: 20, fontWeight: "800", color: palette.ink, marginBottom: 4 }, sheetHint: { fontSize: 12, color: palette.muted, marginBottom: 12 } });
