import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useI18n } from "@/i18n";
import { FButton, FChip, FInput, palette } from "@/ui/foofoo";

const items = [["🫙", "Toor Dal", "750 g", true], ["🫙", "Basmati Rice", "2 kg", false], ["🫙", "Moong Dal", "500 g", false], ["🫙", "Besan", "1 kg", true], ["🌶️", "Red Chilli Powder", "100 g", false], ["🟡", "Turmeric Powder", "200 g", false]] as const;
export default function Pantry() { const { t } = useI18n(); const [filter, setFilter] = useState(t("all")); return <ScrollView style={s.screen} contentContainerStyle={s.page}><View style={s.header}><Text style={s.title}>{t("pantryTitle")}</Text><Pressable onPress={() => router.push("/grocery")}><Text style={s.grocery}>{t("grocery")} ›</Text></Pressable></View><FInput placeholder={`⌕  ${t("searchPantry")}`} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{["all","grains","pulses","spices","others"].map((x) => <FChip key={x} label={t(x as any)} selected={filter === t(x as any)} onPress={() => setFilter(t(x as any))} />)}</ScrollView><View style={s.list}>{items.map(([icon,name,amount,isLow]) => <View key={name} style={s.row}><Text style={s.jar}>{icon}</Text><View style={s.body}><Text style={s.name}>{name}</Text><Text style={s.amount}>{amount}</Text></View><Text style={[s.badge, isLow ? s.low : s.ok]}>{isLow ? t("low") : t("ok")}</Text></View>)}</View><FButton label={t("addItem")} /></ScrollView> }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, page: { padding: 18, paddingBottom: 110, gap: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 }, title: { fontSize: 21, fontWeight: "800", color: palette.ink }, grocery: { color: palette.purple, fontWeight: "700", fontSize: 12 }, chips: { gap: 7 }, list: { backgroundColor: "white", borderRadius: 16, paddingHorizontal: 14, borderWidth: 1, borderColor: palette.line }, row: { flexDirection: "row", alignItems: "center", minHeight: 65, borderBottomWidth: 1, borderBottomColor: palette.line }, jar: { fontSize: 24, width: 40 }, body: { flex: 1 }, name: { fontWeight: "700", color: palette.ink }, amount: { fontSize: 11, color: palette.muted }, badge: { fontSize: 10, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 5, overflow: "hidden" }, low: { color: palette.red, backgroundColor: "#FFF0F2" }, ok: { color: palette.green, backgroundColor: "#EAF8F0" } });
