import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useI18n } from "@/i18n";
import { Avatar, FButton, palette } from "@/ui/foofoo";

export default function Profile() {
  const { t, locale } = useI18n();
  const rows: Array<[string, string, string?]> = [["♧", t("household"), "4"], ["♡", t("foodPrefs")], ["♢", t("allergies")], ["♧", t("reminders")], ["⚙", t("settings")], ["?", t("help")], ["◎", t("language"), locale === "en" ? "English" : "हिंदी"]];
  return <ScrollView style={s.screen} contentContainerStyle={s.page}><Text style={s.title}>{t("profileTitle")}</Text><View style={s.person}><Avatar /><View><Text style={s.name}>Anita Sharma</Text><Text style={s.email}>anita@gmail.com</Text><Text style={s.location}>{t("householdContext")}</Text></View></View><View style={s.context}><Context label={t("plannerRole")} value="Anita" /><Context label={t("cookRole")} value="Sunita" /><Context label={t("cookSpeed")} value={t("fast")} /><Context label={t("regionalIdentity")} value={t("puneMaharashtra")} /></View><View style={s.card}>{rows.map(([icon, label, value]) => <Pressable key={label} style={s.row} onPress={() => label === t("language") ? router.push("/language") : label === t("settings") ? router.push("/settings") : undefined}><Text style={s.icon}>{icon}</Text><Text style={s.label}>{label}</Text>{value ? <Text style={s.value}>{value}</Text> : null}<Text style={s.chev}>›</Text></Pressable>)}</View><Pressable style={s.plus} onPress={() => router.push("/premium")}><Text style={s.plusIcon}>✦</Text><View style={{flex:1}}><Text style={s.plusTitle}>{t("premium")}</Text><Text style={s.plusText}>{t("profilePlusBody")}</Text></View><Text style={s.chev}>›</Text></Pressable><FButton kind="danger" label={t("logout")} /></ScrollView>;
}
function Context({label,value}:{label:string;value:string}){return <View style={s.contextItem}><Text style={s.contextLabel}>{label}</Text><Text numberOfLines={2} style={s.contextValue}>{value}</Text></View>}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, page: { padding: 18, paddingBottom: 110, gap: 18 }, title: { fontSize: 21, fontWeight: "800", marginTop: 8, color: palette.ink }, person: { flexDirection: "row", alignItems: "center", gap: 12 }, name: { fontSize: 16, fontWeight: "800", color: palette.ink }, email: { fontSize: 12, color: palette.muted }, location:{fontSize:9,color:palette.purple,marginTop:2},context:{flexDirection:"row",flexWrap:"wrap",gap:8},contextItem:{width:"48%",padding:11,borderRadius:13,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line},contextLabel:{fontSize:9,color:palette.muted},contextValue:{fontSize:11,fontWeight:"700",color:palette.ink,marginTop:3}, card: { backgroundColor: "white", borderRadius: 16, paddingHorizontal: 14, borderWidth: 1, borderColor: palette.line }, row: { minHeight: 57, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: palette.line, paddingVertical:6 }, icon: { width: 30, color: palette.muted }, label: { flex: 1, fontWeight: "600", color: palette.ink }, value: { fontSize: 12, color: palette.muted }, chev: { fontSize: 23, color: palette.muted, marginLeft: 9 }, plus: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, borderRadius: 16, backgroundColor: palette.purpleSoft }, plusIcon: { fontSize: 22, color: palette.purple }, plusTitle: { fontWeight: "800", color: palette.purple }, plusText: { fontSize: 11, color: palette.muted } });
