"""
ghar_re.seedgen — deterministic SQL seed generator.

Emits two idempotent seed files into database/seeds/ from the single sources of truth
(ghar_re.knowledge = KB transcription, ghar_re.fixtures = golden sample):

  120_ghar_re_kb_reference.sql   — KB/reference data (data_source real/stub per ✓/⚑ + real catalogue)
  121_ghar_re_golden_sample.sql  — invented golden sample (data_source ai_generated)

Deterministic md5(natural_key)::uuid ids (same pattern as database/etl/generate_re_seeds.py) so
FK links resolve without lookups and re-runs are idempotent (ON CONFLICT DO NOTHING).

Run:  python3 -m ghar_re.seedgen
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "data", "source")
SEEDS = os.path.join(ROOT, "database", "seeds")

from ghar_re_core import knowledge as K
from ghar_re_core import fixtures as F


def q(v):
    """SQL literal for a scalar."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def arr(vals):
    """Postgres text[] literal."""
    if vals is None:
        return "NULL"
    inner = ",".join('"' + str(v).replace('"', '\\"') + '"' for v in vals)
    return "ARRAY[" + ",".join(q(v) for v in vals) + "]::text[]" if vals else "ARRAY[]::text[]"


def dish_uuid(name):
    return f"md5('ghar_re.dish:' || {q(name)})::uuid"


def hh_uuid(key):
    return f"md5('ghar_re.hh:' || {q(key)})::uuid"


def combo_uuid(name):
    return f"md5('ghar_re.combo:' || {q(name)})::uuid"


# ---------------------------------------------------------------------------
def load_real_ingredients(used):
    rows = {}
    with open(os.path.join(SRC, "ingredients_v5.csv")) as f:
        for r in csv.DictReader(f):
            if r["name"] in used:
                rows[r["name"]] = r
    return rows


def load_tags():
    out = []
    with open(os.path.join(SRC, "tags_v4.csv")) as f:
        for r in csv.DictReader(f):
            out.append(r)
    return out


def load_community_priors():
    out = []
    with open(os.path.join(SRC, "community_priors.csv")) as f:
        for r in csv.DictReader(f):
            out.append(r)
    return out


# ---------------------------------------------------------------------------
def gen_reference():
    L = []
    L.append("-- Seed: 120_ghar_re_kb_reference.sql  (GENERATED by ghar_re/seedgen.py — do not hand-edit)")
    L.append("-- Ghar RE v1.0 rebuild — KB/reference data transcribed from ghar_knowledge_base_v0_2.md")
    L.append("--   + the real reference CSVs (cuisine_groups_v4, cuisines_v4, tags_v4, ingredients_v5,")
    L.append("--   community_priors.csv). data_source = 'real' for verbatim authored/catalogue values,")
    L.append("--   'stub' for KB ⚑ 'needs refinement' cells. (The 810-dish catalogue is NOT touched.)")
    L.append("-- Idempotent: ON CONFLICT DO NOTHING.\nBEGIN;\n")

    # cuisine_groups (real)
    L.append("-- cuisine_groups (cuisine_groups_v4) [real]")
    with open(os.path.join(SRC, "cuisine_groups_v4 2.csv")) as f:
        for r in csv.DictReader(f):
            L.append(
                f"INSERT INTO ghar_re.cuisine_groups (name, display_name, display_order, description, data_source) "
                f"VALUES ({q(r['name'])}, {q(r['display_name'])}, {q(int(r['display_order']))}, {q(r['description'])}, 'real') "
                f"ON CONFLICT (name) DO NOTHING;"
            )
    L.append("")

    # cuisines (real; only the golden set's cuisines to keep FK closure minimal)
    L.append("-- cuisines (subset from cuisines_v4) [real]")
    for name, disp, grp, parent, state, tier in F.CUISINES:
        L.append(
            f"INSERT INTO ghar_re.cuisines (name, display_name, cuisine_group, parent_cuisine, state_origin, tier, is_user_facing, data_source) "
            f"VALUES ({q(name)}, {q(disp)}, {q(grp)}, {q(parent)}, {q(state)}, {q(tier)}, true, 'real') "
            f"ON CONFLICT (name) DO NOTHING;"
        )
    L.append("")

    # tags (full controlled vocab, real)
    L.append("-- tags (tags_v4 controlled vocabulary) [real]")
    for r in load_tags():
        L.append(
            f"INSERT INTO ghar_re.tags (category, value, display_value, tier, is_user_facing, data_source) "
            f"VALUES ({q(r['category'])}, {q(r['value'])}, {q(r['display_value'])}, {q(r['tier'])}, "
            f"{q(r['is_user_facing']=='Y')}, 'real') ON CONFLICT (category, value) DO NOTHING;"
        )
    L.append("")

    # ingredients master (real attrs from ingredients_v5) for every token the golden dishes use
    used = set()
    for d in F.DISHES:
        for ing, _ in d["ingredients"]:
            used.add(ing)
    ingrows = load_real_ingredients(used)
    L.append("-- ingredients master (ingredients_v5 real attrs; only tokens the golden dishes reference) [real]")
    for name in sorted(used):
        r = ingrows[name]
        L.append(
            f"INSERT INTO ghar_re.ingredients (name, display_name, category, diet_type, is_allergen, allergen_type, is_jain_compatible, is_vegan, data_source) "
            f"VALUES ({q(name)}, {q(r['display_name'])}, {q(r['category'])}, {q(r['diet_type'])}, "
            f"{q(r['is_allergen']=='Y')}, {q(r['allergen_type'] or None)}, {q(r['is_jain_compatible']=='Y')}, "
            f"{q(r['is_vegan']=='Y')}, 'real') ON CONFLICT (name) DO NOTHING;"
        )
    L.append("")

    # zone_map (KB §R1) [real]
    L.append("-- zone_map (KB §R1) [real]")
    for cg, zone, dc, ds in K.ZONE_MAP:
        L.append(
            f"INSERT INTO ghar_re.zone_map (cuisine_group, zone, dish_count, data_source) "
            f"VALUES ({q(cg)}, {q(zone)}, {q(dc)}, {q(ds)}) ON CONFLICT (cuisine_group) DO NOTHING;"
        )
    L.append("")

    # comfort_hero_map (KB §R3) [✓ real / ⚑ stub]
    L.append("-- comfort_hero_map (KB §R3; ✓ verified -> real, ⚑ -> stub). dish_id linked in seed 121.")
    for zone, weather, name, verified, ds in K.COMFORT_HERO_MAP:
        L.append(
            f"INSERT INTO ghar_re.comfort_hero_map (zone, weather_type, dish_name, verified_flag, data_source) "
            f"VALUES ({q(zone)}, {q(weather)}, {q(name)}, {q(verified)}, {q(ds)}) "
            f"ON CONFLICT (zone, weather_type, dish_name) DO NOTHING;"
        )
    L.append("")

    # sig_score_bands (KB §S1 rule) [real]
    L.append("-- sig_score_bands (KB §S1 calibration RULE) [real]")
    for score, band, defn, ds in K.SIG_SCORE_BANDS:
        L.append(
            f"INSERT INTO ghar_re.sig_score_bands (score, band_name, definition, data_source) "
            f"VALUES ({q(score)}, {q(band)}, {q(defn)}, {q(ds)}) ON CONFLICT (score) DO NOTHING;"
        )
    L.append("")

    # negative_priors (KB §N1) [real]
    L.append("-- negative_priors (KB §N1; in_spine rows enforced via pairing_rules.yaml; 2 rows deferred_v2)")
    for disc, ctx, act, insp, via, status, ds in K.NEGATIVE_PRIORS:
        L.append(
            f"INSERT INTO ghar_re.negative_priors (discouragement, context, action, in_spine, enforced_via, status, data_source) "
            f"VALUES ({q(disc)}, {q(ctx)}, {q(act)}, {q(insp)}, {q(via)}, {q(status)}, {q(ds)});"
        )
    L.append("")

    # prior_zone_slot_season (KB §R2) [real/stub]
    L.append("-- prior_zone_slot_season (KB §R2 PRIOR[zone][slot]; ⚑ East breakfast -> stub). season NULL (2-D).")
    for zone, slot, mk, mv, boost, tags, ds in K.PRIOR_ZONE_SLOT:
        L.append(
            f"INSERT INTO ghar_re.prior_zone_slot_season (zone, slot, season, match_kind, match_value, boost, usage_tags, data_source) "
            f"VALUES ({q(zone)}, {q(slot)}, NULL, {q(mk)}, {q(mv)}, {q(boost)}, {arr(tags)}, {q(ds)});"
        )
    L.append("")

    # community_priors (community_priors.csv / KB §C1) [real]
    L.append("-- community_priors (community_priors.csv, KB §C1; soft, overridden by Q5-Q8) [real]")
    for r in load_community_priors():
        L.append(
            f"INSERT INTO ghar_re.community_priors (state, zone, diet_lean, default_non_veg_cadence, data_source) "
            f"VALUES ({q(r['state'])}, {q(r['zone'])}, {q(r['diet_lean'])}, {q(r['default_non_veg_cadence'])}, 'real') "
            f"ON CONFLICT (state) DO NOTHING;"
        )
    L.append("")

    # ingredient_normalization_map (KB §E1) [real/stub]
    L.append("-- ingredient_normalization_map (KB §E1; expansion row ⚑ -> stub) [real/stub]")
    for tok, canon, ntype, expn, note, ds in K.INGREDIENT_NORMALIZATION:
        L.append(
            f"INSERT INTO ghar_re.ingredient_normalization_map (surface_token, canonical, norm_type, expansion, note, data_source) "
            f"VALUES ({q(tok)}, {q(canon)}, {q(ntype)}, {arr(expn)}, {q(note)}, {q(ds)}) "
            f"ON CONFLICT (surface_token, norm_type) DO NOTHING;"
        )

    L.append("\nCOMMIT;")
    return "\n".join(L) + "\n"


def gen_golden():
    from ghar_re_core.knowledge import BAND_TO_SCORE
    L = []
    L.append("-- Seed: 121_ghar_re_golden_sample.sql  (GENERATED by ghar_re/seedgen.py — do not hand-edit)")
    L.append("-- Ghar RE v1.0 rebuild — GOLDEN SAMPLE (invented, clearly flagged).")
    L.append("-- EVERY row here is data_source='ai_generated' (Task 2). The real 810-dish catalogue is untouched.")
    L.append("-- Idempotent: ON CONFLICT DO NOTHING. Requires seed 120 (reference) first.\nBEGIN;\n")

    # dishes
    L.append("-- dishes [ai_generated]")
    for d in F.DISHES:
        L.append(
            "INSERT INTO ghar_re.dishes (id, name, short_description, alternate_names, cuisine, "
            "spice_level, sweetness, heaviness, difficulty, prep_mins, cook_mins, total_mins, calories, "
            "serving_size, meal_type, dish_category, cooking_method, primary_taste, texture, richness, "
            "mouthfeel, aroma_profile, fermentation, serving_temp, weather_affinity, diet, hero_role, "
            "jain_compatible, scope_tier, farali_compatible, is_active, data_source) VALUES ("
            f"{dish_uuid(d['name'])}, {q(d['name'])}, {q(d.get('short_description'))}, {arr(d['alternate_names'])}, "
            f"{q(d['cuisine'])}, {q(d['spice_level'])}, {q(d['sweetness'])}, {q(d['heaviness'])}, {q(d['difficulty'])}, "
            f"{q(d['prep_mins'])}, {q(d['cook_mins'])}, {q(d['total_mins'])}, {q(d['calories'])}, {q(d['serving_size'])}, "
            f"{arr(d['meal_type'])}, {arr(d['dish_category'])}, {arr(d['cooking_method'])}, {arr(d['primary_taste'])}, "
            f"{arr(d['texture'])}, {arr(d['richness'])}, {arr(d['mouthfeel'])}, {arr(d['aroma_profile'])}, "
            f"{q(d['fermentation'])}, {q(d['serving_temp'])}, {arr(d['weather_affinity'])}, {q(d['diet'])}, "
            f"{q(d['hero_role'])}, {q(d['jain_compatible'])}, {q(d['scope_tier'])}, {q(d['farali_compatible'])}, "
            "true, 'ai_generated') ON CONFLICT (id) DO NOTHING;"
        )
    L.append("")

    # dish_ingredients + dish_name_synonyms + dish_macro + sig_scores
    L.append("-- dish_ingredients [ai_generated]  (ingredient master rows are real; the LINK is invented)")
    for d in F.DISHES:
        for ing, is_main in d["ingredients"]:
            L.append(
                f"INSERT INTO ghar_re.dish_ingredients (dish_id, ingredient_name, is_main_ingredient, data_source) "
                f"VALUES ({dish_uuid(d['name'])}, {q(ing)}, {q(is_main)}, 'ai_generated') ON CONFLICT DO NOTHING;"
            )
    L.append("")
    L.append("-- dish_name_synonyms [ai_generated]")
    for d in F.DISHES:
        for syn in d.get("synonyms", []):
            L.append(
                f"INSERT INTO ghar_re.dish_name_synonyms (dish_id, synonym, data_source) "
                f"VALUES ({dish_uuid(d['name'])}, {q(syn)}, 'ai_generated') ON CONFLICT DO NOTHING;"
            )
    L.append("")
    L.append("-- dish_macro [ai_generated]")
    for d in F.DISHES:
        m = d["macro"]
        L.append(
            f"INSERT INTO ghar_re.dish_macro (dish_id, calories, protein_g, fibre_g, fat_g, carbs_g, sugar_g, sodium_mg, data_source) "
            f"VALUES ({dish_uuid(d['name'])}, {q(m['calories'])}, {q(m['protein_g'])}, {q(m['fibre_g'])}, {q(m['fat_g'])}, "
            f"{q(m['carbs_g'])}, {q(m['sugar_g'])}, {q(m['sodium_mg'])}, 'ai_generated') ON CONFLICT (dish_id) DO NOTHING;"
        )
    L.append("")
    L.append("-- sig_scores [ai_generated]  (band ASSIGNED to invented dish; score from KB §S1 rule)")
    for d in F.DISHES:
        band = d["sig_band"]
        score = BAND_TO_SCORE[band]
        L.append(
            f"INSERT INTO ghar_re.sig_scores (dish_id, sig_score, band, evidence_confidence, coverage_confidence, owner, method, version, data_source) "
            f"VALUES ({dish_uuid(d['name'])}, {q(score)}, {q(band)}, 'Low', 'High', 'golden-sample', 'ai_generated', 'v1.0', 'ai_generated') "
            f"ON CONFLICT (dish_id) DO NOTHING;"
        )
    L.append("")

    # region_food_affinity (golden)
    L.append("-- region_food_affinity [ai_generated]")
    for state_code, dish_name, score in F.REGION_AFFINITY:
        L.append(
            f"INSERT INTO ghar_re.region_food_affinity (state_code, dish_name, affinity_score, source, data_source) "
            f"VALUES ({q(state_code)}, {q(dish_name)}, {q(score)}, 'golden-sample', 'ai_generated') "
            f"ON CONFLICT (state_code, dish_name) DO NOTHING;"
        )
    L.append("")

    # dish_variants (a couple, to exercise the substitution graph) [ai_generated]
    L.append("-- dish_variants [ai_generated] (substitution graph seed rows)")
    variants = [
        ("Chettinad Chicken", "Paneer Butter Masala", "veg_swap", "non-veg -> veg single on veg-day"),
        ("Onion Pakora", "Medu Vada", "veg_swap", "North fried snack -> South fried snack analogue"),
    ]
    for frm, to, vt, note in variants:
        L.append(
            f"INSERT INTO ghar_re.dish_variants (from_dish_id, to_dish_id, variant_type, note, data_source) "
            f"VALUES ({dish_uuid(frm)}, {dish_uuid(to)}, {q(vt)}, {q(note)}, 'ai_generated') "
            f"ON CONFLICT (from_dish_id, to_dish_id, variant_type) DO NOTHING;"
        )
    L.append("")

    # link comfort_hero_map.dish_id to golden dishes by exact name (reference rows keep their data_source)
    L.append("-- link comfort_hero_map.dish_id to golden dishes named after KB §R3 heroes")
    hero_links = ["Onion Pakora", "Sarson Ka Saag", "Kanda Bhaji", "Curd Rice", "Rasam",
                  "Medu Vada", "Bhuna Khichuri", "Undhiyu", "Pithla"]
    # Match KB names -> golden dish names (KB uses 'Pakora','Khichuri','Rasam'/'Rasam-Rice' etc.)
    name_map = {
        "Pakora": "Onion Pakora", "Sarson Ka Saag": "Sarson Ka Saag", "Kanda Bhaji": "Kanda Bhaji",
        "Curd Rice": "Curd Rice", "Rasam": "Rasam", "Rasam-Rice": "Rasam", "Medu Vada": "Medu Vada",
        "Khichuri": "Bhuna Khichuri", "Undhiyu": "Undhiyu", "Pithla": "Pithla",
    }
    for kb_name, dish_name in name_map.items():
        L.append(
            f"UPDATE ghar_re.comfort_hero_map SET dish_id = {dish_uuid(dish_name)} "
            f"WHERE dish_name = {q(kb_name)} AND dish_id IS NULL;"
        )
    L.append("")

    # households + household_modes
    L.append("-- households (raw Q1-Q15) [ai_generated]")
    import json
    for h in F.HOUSEHOLDS:
        L.append(
            "INSERT INTO ghar_re.households (id, label, q1_household_type, q2_working_professionals, q3_home_state, "
            "q4_current_city, q5_diet, q6_nonveg_types, q7_veg_days, q8_is_jain, q9_allergies, q11_conditions, "
            "q12_member_ages, q13_who_cooks, q14_eat_out_per_week, q15_objective, data_source) VALUES ("
            f"{hh_uuid(h['id_key'])}, {q(h['label'])}, {q(h['q1_household_type'])}, {q(h['q2_working_professionals'])}, "
            f"{q(h['q3_home_state'])}, {q(h['q4_current_city'])}, {q(h['q5_diet'])}, {arr(h['q6_nonveg_types'])}, "
            f"{arr(h['q7_veg_days'])}, {q(h['q8_is_jain'])}, {arr(h['q9_allergies'])}, {arr(h['q11_conditions'])}, "
            f"{q(json.dumps(h['q12_member_ages']))}::jsonb, {q(h['q13_who_cooks'])}, {q(h['q14_eat_out_per_week'])}, "
            f"{q(h['q15_objective'])}, 'ai_generated') ON CONFLICT (id) DO NOTHING;"
        )
    L.append("")
    L.append("-- household_modes [ai_generated] (Jain household not a mode; veg_egg off by default here)")
    L.append("")

    L.append("COMMIT;")
    return "\n".join(L) + "\n"


def main():
    os.makedirs(SEEDS, exist_ok=True)
    ref = gen_reference()
    gold = gen_golden()
    with open(os.path.join(SEEDS, "120_ghar_re_kb_reference.sql"), "w") as f:
        f.write(ref)
    with open(os.path.join(SEEDS, "121_ghar_re_golden_sample.sql"), "w") as f:
        f.write(gold)
    print("wrote 120_ghar_re_kb_reference.sql (%d bytes)" % len(ref))
    print("wrote 121_ghar_re_golden_sample.sql (%d bytes)" % len(gold))


if __name__ == "__main__":
    main()
