-- Rollback 106 (cascades to dish_ingredients/dish_tags via ON DELETE CASCADE)
-- WP-6E teardown finding: fn_derive_dish_attributes (migration 010) logs intermediate
-- derivation states into public.derivation_conflicts during row-by-row dish_ingredients
-- seeding; those audit rows FK-reference dishes(id) WITHOUT cascade, so they must be cleared
-- before dishes can be deleted. These rows are seed-load audit artifacts for exactly the
-- dishes this rollback removes.
BEGIN;
DELETE FROM public.derivation_conflicts;
DELETE FROM public.dishes WHERE name IN (
  'Butter Chicken',
  'Dal Makhani',
  'Sarson Ka Saag',
  'Makki Ki Roti',
  'Tandoori Chicken',
  'Paneer Tikka',
  'Amritsari Fish Fry',
  'Chole',
  'Rajma',
  'Palak Paneer',
  'Aloo Gobhi',
  'Paneer Butter Masala',
  'Shahi Paneer',
  'Chicken Tikka',
  'Seekh Kebab',
  'Kadhi Pakora',
  'Aloo Paratha',
  'Gobhi Paratha',
  'Paneer Paratha',
  'Naan',
  'Garlic Naan',
  'Kulcha',
  'Lassi (Sweet)',
  'Lassi (Salted)',
  'Matar Paneer',
  'Dal Tadka',
  'Bhindi Masala',
  'Baingan Bharta',
  'Dum Aloo',
  'Jeera Rice',
  'Pindi Chole',
  'Chicken Curry',
  'Keema Matar',
  'Phulka',
  'Tawa Chicken',
  'Bhatura',
  'Bedmi Puri',
  'Aloo Sabzi (Delhi style)',
  'Dahi Bhalla',
  'Aloo Tikki',
  'Pav Bhaji (Delhi style)',
  'Parantha (Plain)',
  'Mooli Paratha',
  'Chur Chur Naan',
  'Chaat Papdi',
  'Kachori (Dal)',
  'Bhel Puri',
  'Sev Puri',
  'Egg Bhurji',
  'Egg Curry',
  'Mughlai Paratha',
  'Rabri Jalebi',
  'Kulfi Falooda',
  'Rumali Roti',
  'Nihari',
  'Mutton Korma',
  'Biryani (Mughlai Chicken)',
  'Shami Kebab',
  'Mughlai Chicken',
  'Pasanda',
  'Mutton Rogan Josh',
  'Galouti Kebab',
  'Kakori Kebab',
  'Lucknowi Biryani',
  'Tunday Kebab',
  'Chicken Stew (Awadhi)',
  'Nahari Kulcha',
  'Sheermal',
  'Zarda',
  'Phirni',
  'Haleem',
  'Rezala',
  'Baida Roti',
  'Warqi Paratha',
  'Hyderabadi Chicken Biryani',
  'Hyderabadi Mutton Biryani',
  'Mirchi Ka Salan',
  'Double Ka Meetha',
  'Bagara Baingan',
  'Pathar Ka Gosht',
  'Lukhmi',
  'Khubani Ka Meetha',
  'Hyderabadi Marag',
  'Dalcha',
  'Osmania Biscuit',
  'Dum Ka Murgh',
  'Bagara Khana',
  'Hyderabadi Egg Biryani',
  'Irani Chai',
  'Tahari',
  'Qubani Ka Meetha',
  'Achari Gosht',
  'Masala Dosa',
  'Plain Dosa',
  'Idli',
  'Sambar',
  'Rasam',
  'Coconut Chutney',
  'Medu Vada',
  'Uttapam',
  'Pongal (Ven)',
  'Pongal (Sweet)',
  'Curd Rice',
  'Lemon Rice',
  'Tamarind Rice',
  'Tomato Rice',
  'Kootu',
  'Poriyal',
  'Avial',
  'Kuzhambu (Vathal)',
  'Payasam (Semiya)',
  'Appam',
  'Rasam Vada',
  'Chicken Chettinad',
  'Chettinad Egg Curry',
  'Paniyaram',
  'Murukku',
  'Kothu Parotta',
  'Parotta (Kerala/Tamil)',
  'Filter Coffee',
  'Sundal',
  'Kerala Fish Curry',
  'Appam with Stew',
  'Puttu',
  'Kadala Curry',
  'Fish Molee',
  'Kerala Prawn Curry',
  'Avial (Kerala)',
  'Olan',
  'Parippu Curry',
  'Banana Chips',
  'Kerala Parotta',
  'Beef Fry (Kerala)',
  'Payasam (Ada)',
  'Palada Payasam',
  'Malabar Biryani',
  'Pathiri',
  'Unniyappam',
  'Erissery',
  'Mutta Curry',
  'Bisi Bele Bath',
  'Ragi Mudde',
  'Neer Dosa',
  'Jolada Rotti',
  'Chitranna',
  'Set Dosa',
  'Goli Baje',
  'Akki Rotti',
  'Mangalorean Fish Gassi',
  'Kori Rotti',
  'Mysore Pak',
  'Obbattu',
  'Vangi Bath',
  'Kesari Bath',
  'Saaru',
  'Machher Jhol',
  'Shorshe Ilish',
  'Aloo Posto',
  'Luchi',
  'Cholar Dal',
  'Kosha Mangsho',
  'Mishti Doi',
  'Sandesh',
  'Rasgulla',
  'Begun Bhaja',
  'Chingri Malai Curry',
  'Doi Maach',
  'Shukto',
  'Macher Kalia',
  'Pitha (Patishapta)',
  'Ghugni',
  'Mochar Ghonto',
  'Aam Doi',
  'Steamed Rice',
  'Muri Ghonto',
  'Vada Pav',
  'Misal Pav',
  'Puran Poli',
  'Thalipeeth',
  'Sabudana Khichdi',
  'Poha',
  'Usal',
  'Bhakri',
  'Pav Bhaji',
  'Batata Vada',
  'Bharli Vangi',
  'Sol Kadhi',
  'Amti',
  'Kombdi Vade (Malvani)',
  'Tambda Rassa',
  'Pandhra Rassa',
  'Modak',
  'Shrikhand',
  'Ukdiche Modak',
  'Kothimbir Vadi',
  'Dhokla',
  'Thepla',
  'Undhiyu',
  'Khandvi',
  'Fafda Jalebi',
  'Dal Dhokli',
  'Gujarati Kadhi',
  'Sev Tamatar',
  'Handvo',
  'Patra',
  'Basundi',
  'Gathiya',
  'Mohanthal',
  'Khakhra',
  'Aam Shrikhand',
  'Rotla',
  'Methi Na Gota',
  'Khichu',
  'Muthiya',
  'Goan Fish Curry',
  'Vindaloo (Pork)',
  'Xacuti (Chicken)',
  'Bebinca',
  'Sorpotel',
  'Ros Omelette',
  'Fish Recheado',
  'Pao (Goan Bread)',
  'Prawn Balchao',
  'Goan Prawn Curry',
  'Chicken Cafreal',
  'Sannas',
  'Samosa',
  'Kathi Roll',
  'Pakora (Mixed Veg)',
  'Pani Puri',
  'Bread Pakora',
  'Chole Tikki',
  'Ragda Pattice',
  'Momos (Steamed Veg)',
  'Momos (Chicken)',
  'Fried Momos',
  'Dosa (Street Style)',
  'Egg Roll',
  'Jalebi',
  'Gulab Jamun',
  'Gajar Ka Halwa',
  'Hakka Noodles',
  'Veg Fried Rice',
  'Manchurian (Veg)',
  'Chilli Chicken',
  'Chilli Paneer',
  'Manchow Soup (Veg)',
  'Spring Roll',
  'Chicken Fried Rice',
  'Chicken Manchurian',
  'Paneer 65',
  'Honey Chilli Potato',
  'Schezwan Noodles',
  'Paneer Chilli Dry',
  'Dragon Chicken',
  'Dal Baati',
  'Churma',
  'Laal Maas',
  'Gatte Ki Sabzi',
  'Ker Sangri',
  'Pyaaz Ki Kachori',
  'Achari Paneer',
  'Papad Ki Sabzi',
  'Bajra Roti',
  'Barfi (Kaju)',
  'Pasta Arrabiata',
  'Margherita Pizza',
  'Pasta Alfredo',
  'Garlic Bread',
  'Bruschetta',
  'Grilled Chicken',
  'Caesar Salad',
  'Mushroom Soup',
  'French Fries',
  'Grilled Sandwich',
  'Paneer Steak',
  'Tomato Soup',
  'Veg Burger',
  'Maggi Noodles',
  'Chicken Burger',
  'Rogan Josh',
  'Dum Aloo (Kashmiri)',
  'Yakhni',
  'Kahwa',
  'Noon Chai',
  'Gushtaba',
  'Modur Pulao',
  'Haak (Kashmiri Greens)',
  'Bhakarwadi',
  'Gongura Chicken',
  'Pulihora',
  'Gutti Vankaya',
  'Andhra Chicken Curry',
  'Boti Kebab',
  'Cham Cham',
  'Sakinalu',
  'Natu Kodi Pulusu',
  'Litti Chokha',
  'Sattu Paratha',
  'Thekua',
  'Dal Pitha',
  'Chana Ghugni',
  'Chapli Kebab',
  'Koki',
  'Bhutte Ka Kees',
  'Parsi Dhansak',
  'Stuffed Capsicum',
  'Chicken Changezi',
  'Mix Veg',
  'Chicken Soup',
  'Chikki (Peanut)',
  'Dabeli',
  'Onion Dosa',
  'Ghee Roast Dosa',
  'Mysore Masala Dosa',
  'Rava Upma',
  'Idiyappam',
  'Kerala Egg Roast',
  'Thoran (Cabbage)',
  'Meen Pollichathu',
  'Manga Curry',
  'Vazhakka Bajji',
  'Vengaya Sambar',
  'Bombay Sandwich',
  'Kolkata Biryani',
  'Chingri Bhaja',
  'Posto Bora',
  'Dhokar Dalna',
  'Chanar Dalna',
  'Jhalmuri',
  'Payesh',
  'Telebhaja Platter',
  'Aamti (Kokum)',
  'Pithla',
  'Matki Usal',
  'Aamras',
  'Chakli',
  'Sabudana Vada',
  'Kolhapuri Misal',
  'Daulat Ki Chaat',
  'Khichu (Papdi No Lot)',
  'Lilva Kachori',
  'Dudhi Halwa',
  'Chicken Korma',
  'Egg Fried Rice',
  'Ghevar',
  'Kathi Kebab Wrap',
  'Gongura Pachadi',
  'Mutton Nihari',
  'Sheermal with Nihari',
  'Gujarati Dal',
  'Biryani Rice (Plain)',
  'Hot and Sour Soup',
  'Hyderabadi Kheer',
  'Kheer',
  'Ras Malai',
  'Sohan Halwa',
  'Kulfi (Malai)',
  'Hyderabadi Haleem',
  'Hyderabadi Keema Samosa',
  'Hyderabadi Khichdi',
  'Aloo Chaat',
  'Papdi Chaat',
  'Imarti',
  'Crispy Corn',
  'Veg Manchow Soup',
  'Chicken Lollipop',
  'Chilli Fish',
  'Chicken 65',
  'Tahiri',
  'Khichdi',
  'Puri',
  'Aloo Puri',
  'Baati Chokha',
  'Goan Sausage Pulao',
  'Chicken Xacuti',
  'Fried Bombil',
  'Ambot Tik',
  'Feni Spiked Cashew Curry',
  'Kachhi Haldi Ki Sabzi',
  'Makhaniya Lassi',
  'Methi Bajra Puri',
  'Jonna Rotte',
  'Nadru Yakhni',
  'Goshtaba',
  'Kashmiri Pulao',
  'Pepper Chicken',
  'Kozhi Varuval',
  'Thayir Vadai',
  'Vendakkai Poriyal',
  'Paruppu Rasam',
  'Keerai Masiyal',
  'Mor Kuzhambu',
  'Bisi Bele Bath Mix Veg',
  'Kerala Chicken Curry',
  'Pazhampori',
  'Egg Podimas',
  'Aloo Dum (Bengali)',
  'Macher Matha Diye Moong Dal',
  'Chhanar Jilipi',
  'Tok Dal',
  'Chingri Cutlet',
  'Masala Bhaat',
  'Kadhai Chicken',
  'Thalipeeth (Multi-grain)',
  'Kolambi Bhaat',
  'Solkadhi',
  'Kadhai Paneer',
  'Patra Ni Machhi',
  'Salli Boti',
  'Akuri',
  'Butter Naan',
  'Stuffed Naan (Paneer)',
  'Chicken Malai Tikka',
  'Tandoori Paneer Tikka',
  'Chana Chaat',
  'Shahi Tukda',
  'Aloo Chhole',
  'Paneer Bhurji',
  'Tandoori Roti',
  'Hyderabadi Mirchi Bajji',
  'Andhra Prawn Fry',
  'Pesarattu Upma',
  'Bobbatlu',
  'Pachi Pulusu',
  'Laccha Paratha',
  'Mag Ni Dal',
  'Veg Club Sandwich',
  'Malai Kofta',
  'Masala Omelette',
  'Boiled Egg',
  'Chai',
  'Kadai Paneer',
  'Chaas',
  'Hyderabadi Biryani (Veg)',
  'Pasta Carbonara',
  'Gnocchi in Tomato Sauce',
  'Ravioli (Spinach Ricotta)',
  'Arancini',
  'Frittata',
  'Cannoli',
  'Gelato',
  'Panini (Grilled Veg)',
  'Fettuccine Alfredo',
  'Cacio e Pepe',
  'Pasta Pomodoro',
  'Panzanella',
  'Spaghetti Bolognese',
  'Italian Meatballs',
  'Chicken Parmesan',
  'Tortellini Soup',
  'Panini (Chicken)',
  'Insalata Mista',
  'Minestrone Soup',
  'Focaccia',
  'Ciabatta',
  'Caprese Salad',
  'Affogato',
  'Tiramisu',
  'Marinara Breadsticks',
  'Cream of Tomato Soup',
  'Broccoli Soup',
  'French Onion Soup',
  'Corn Chowder',
  'Greek Salad',
  'Coleslaw',
  'Garden Salad',
  'Pasta Salad',
  'Mashed Potatoes',
  'Mac and Cheese',
  'Nachos with Salsa',
  'Chicken Steak',
  'Fish and Chips',
  'Lamb Chops',
  'Chicken Nuggets',
  'Potato Wedges',
  'Onion Rings',
  'Waffles',
  'Quiche (Vegetable)',
  'Scrambled Eggs on Toast',
  'French Omelette',
  'Chicken Wrap',
  'Pancakes',
  'Malpua',
  'Chilli Garlic Noodles',
  'Veg Crispy',
  'Burnt Garlic Fried Rice',
  'Paneer Chilli Gravy',
  'Mushroom Chilli',
  'Baby Corn Manchurian',
  'Egg Chilli',
  'Chicken Schezwan Noodles',
  'Dragon Prawns',
  'Prawn Hakka Noodles',
  'American Chop Suey',
  'Veg Manchurian Dry',
  'Mawa Kachori',
  'Wonton Soup',
  'Dim Sum (Veg)',
  'Szechuan Chicken',
  'Kung Pao Chicken',
  'Sweet and Sour Chicken',
  'Mapo Tofu',
  'Steamed Bao (Veg)',
  'Chicken Satay',
  'Vegetable Stir Fry',
  'Noodle Soup',
  'Egg Drop Soup',
  'Szechuan Fried Rice',
  'Bread Omelette',
  'Corn Chaat',
  'Raj Kachori',
  'Matar Chaat',
  'Hara Bhara Kebab',
  'Paneer Tikka Roll',
  'Masala Papad',
  'Aloo Bonda',
  'Veg Cutlet',
  'Toast Sandwich',
  'Keema Samosa',
  'Chicken Roll (Kolkata)',
  'Mutton Roll',
  'Fish Fry (Street Style)',
  'Egg Paratha',
  'Egg Bhurji Pav',
  'Omelette Pav',
  'Boiled Egg Chaat',
  'Kulfi (Paan)',
  'Balushahi',
  'Gujiya',
  'Meen Kulambu',
  'Methi Matar Malai',
  'Mirchi Vada',
  'Thandai',
  'Fruit Chaat',
  'Falooda',
  'Tandoori Momos',
  'Missi Roti',
  'Kurkure Bhindi',
  'Bhutta (Roasted Corn)',
  'Miso Soup',
  'Ramen (Chicken)',
  'Tempura (Veg)',
  'Sushi (Veg Roll)',
  'Edamame',
  'Teriyaki Chicken',
  'Gyoza',
  'Katsu Curry',
  'Yakitori',
  'Japanese Fried Rice',
  'Udon Noodles',
  'Onigiri',
  'Chicken Karaage',
  'Okonomiyaki',
  'Mochi',
  'Pad Thai (Veg)',
  'Green Curry (Veg)',
  'Red Curry (Chicken)',
  'Tom Yum Soup (Prawn)',
  'Tom Kha Gai',
  'Thai Fried Rice (Chicken)',
  'Som Tam',
  'Thai Basil Chicken',
  'Pad See Ew',
  'Massaman Curry',
  'Thai Fish Cakes',
  'Mango Sticky Rice',
  'Kimchi Fried Rice',
  'Tteokbokki',
  'Japchae',
  'Korean Fried Chicken',
  'Bulgogi',
  'Bibimbap (Veg)',
  'Bibimbap (Chicken)',
  'Dakgalbi',
  'Gyeran Mari',
  'Korean Corn Cheese',
  'Pho (Chicken)',
  'Banh Mi (Pork)',
  'Vietnamese Spring Roll (Fresh)',
  'Banh Xeo',
  'Bun Cha',
  'Vietnamese Coffee',
  'Tofu Pho',
  'Com Tam',
  'Hummus',
  'Falafel',
  'Shawarma (Chicken)',
  'Tabbouleh',
  'Baba Ganoush',
  'Pita Bread',
  'Fattoush',
  'Kofta Kebab',
  'Chicken Shawarma Plate',
  'Stuffed Grape Leaves',
  'Chicken Tacos',
  'Chicken Burrito',
  'Quesadilla (Veg)',
  'Guacamole',
  'Bean Burrito',
  'Mexican Rice',
  'Chicken Enchilada',
  'Churros',
  'Khow Suey',
  'Mohinga',
  'Burmese Tea Leaf Salad',
  'Shan Noodles',
  'Burmese Samosa Soup',
  'Ema Datshi',
  'Kewa Datshi',
  'Phaksha Paa',
  'Jasha Maroo',
  'Masor Tenga',
  'Aloo Pitika',
  'Khar',
  'Duck Curry (Assamese)',
  'Pork with Bamboo Shoot',
  'Ou Tenga Fish Curry',
  'Til Pitha',
  'Kumura Khar',
  'Bora Saul Rice',
  'Narikol Laru',
  'Smoked Pork with Bamboo Shoot',
  'Naga Pork Curry',
  'Axone Chutney',
  'Raja Mirchi Chutney',
  'Galho',
  'Anishi Curry',
  'Naga Fish Curry',
  'Smoked Chicken (Naga)',
  'Eromba',
  'Singju',
  'Kangshoi',
  'Chamthong',
  'Paknam',
  'Gundruk Soup',
  'Sel Roti',
  'Chhurpi Soup',
  'Kinema Curry',
  'Phagshapa',
  'Jadoh',
  'Tungrymbai',
  'Dohneiiong',
  'Nakham Bitchi',
  'Bai',
  'Sawhchiar',
  'Koat Pitha',
  'Thukpa (Arunachali)',
  'Pika Pila',
  'Lukter',
  'Mui Borok',
  'Berma',
  'Wahan Mosdeng',
  'Dalma',
  'Pakhala Bhaat',
  'Chhena Poda',
  'Rasabali',
  'Santula',
  'Machha Besara',
  'Saga Bhaja',
  'Enduri Pitha',
  'Khaja (Odia)',
  'Machha Jhola',
  'Kosha Murgi',
  'Daab Chingri',
  'Ilish Bhaja',
  'Fish Chop',
  'Prawn Malaikari',
  'Mutton Chaap',
  'Kolkata Chicken Roll',
  'Kolkata Fish Fry',
  'Labra',
  'Narkel Naru',
  'Sondesh (Nolen Gur)',
  'Pantua',
  'Rajbhog',
  'Shukni',
  'Bhopali Gosht Korma',
  'Bhopali Biryani',
  'Mawa Bati',
  'Bhopali Kebab',
  'Chakki Ki Shaak',
  'Shahi Shikanji',
  'Indori Namkeen',
  'Garadu Chaat',
  'Khopra Patties',
  'Shikanji (Indori)',
  'Indori Poha',
  'Fara',
  'Muthiya (CG)',
  'Bore Baasi',
  'Aamat',
  'Chila (CG)',
  'Angakar Roti',
  'Dubki Kadhi',
  'Bhutte Ka Kees (Indori)',
  'Gongura Mutton',
  'Punugulu',
  'Royyala Iguru',
  'Chepala Pulusu',
  'Natukodi Fry',
  'Dappalam',
  'Uggani',
  'Gavvalu',
  'Ariselu',
  'Sakinalu (Telangana)',
  'Murgh Musallam',
  'Mutton Biryani (Lucknowi)',
  'Paneer Do Pyaza',
  'Bellam Garelu',
  'Pootharekulu',
  'Borugu Undalu',
  'Mamsam Pulusu',
  'Pesarattu MLC',
  'Chettinad Fish Curry',
  'Chettinad Mutton',
  'Athirasam',
  'Kavuni Arisi',
  'Chicken Sukka (Chettinad)',
  'Chicken Ghee Roast',
  'Prawn Sukka',
  'Pundi Curry',
  'Mangalore Buns',
  'Mushroom Ghee Roast',
  'Rava Idli',
  'Saagu',
  'Uddina Vada (Udupi)',
  'Meen Mappas',
  'Irachi Stew',
  'Pathiri (Malabar)',
  'Koottu Curry',
  'Theeyal',
  'Chakka Pradhaman',
  'Meen Varuthathu',
  'Lyodur Tschaman',
  'Rishta',
  'Aab Gosht',
  'Tchok Wangan',
  'Rajasthani Pyaaz Kachori',
  'Paneer Manchurian',
  'Pakodi Ki Kadhi',
  'Bajra Khichdi',
  'Mohan Thaal',
  'Peda',
  'Besan Gatte',
  'Bajra Roti (Rajasthani)',
  'Banarasi Chaat',
  'Banarasi Thandai',
  'Matar Ki Tikki',
  'Tamatar Chaat',
  'Revdi',
  'Gujhiya',
  'Lucknowi Kebab Paratha',
  'Dham Thali',
  'Madra (Chana)',
  'Babru',
  'Siddu',
  'Aktori',
  'Chha Gosht',
  'Tudkiya Bhath',
  'Kafuli',
  'Bhatt Ki Churkani',
  'Chainsoo',
  'Jhangora Kheer',
  'Bal Mithai',
  'Singodi',
  'Phaanu',
  'Dubuk',
  'Patande',
  'Bihari Kebab',
  'Kadhi Badi (Bihari)',
  'Goan Egg Curry',
  'Poee Bread',
  'Serradura',
  'Dodol',
  'Berry Pulao',
  'Lagan Nu Custard',
  'Sev Biryanji',
  'Tisrya Masala',
  'Malvani Mutton Curry',
  'Masala Bhaat (Maharashtrian)',
  'Pesarattu',
  'Sabudana Vada (Maharashtrian)',
  'Aamras (Maharashtrian)',
  'Rabri',
  'Ram Ladoo',
  'Rava Dosa',
  'Safed Maas',
  'Sai Bhaji',
  'Koki (Sindhi)',
  'Chicken Korma (Mughlai)',
  'Sarva Pindi',
  'Sev Usal',
  'Shakarkandi Chaat',
  'Shikampur Kebab',
  'Sindhi Kadhi',
  'Surti Locho',
  'Sweet Corn Soup',
  'Taar Gosht',
  'Tabak Maaz',
  'Upma',
  'Pepper Chicken (Tamil)'
);
COMMIT;
