-- Rollback 109 (items cascade with combos)
BEGIN;
DELETE FROM public.dish_combos WHERE combo_name IN (
  'Chole Bhature',
  'Rajma Chawal',
  'Dal Chawal',
  'Idli Sambar',
  'Masala Dosa Set',
  'Dosa Sambar',
  'Medu Vada Sambar',
  'Dal Baati Churma',
  'Sarson Ka Saag Makki Ki Roti',
  'Poha Jalebi',
  'Chole Kulche',
  'Puri Aloo',
  'Bedmi Puri Aloo',
  'Kerala Rice Meals',
  'Hyderabadi Biryani Set',
  'Puttu Kadala',
  'Paratha Curd Pickle',
  'Matar Kulcha',
  'Chole Bhature (Delhi)',
  'Nihari Kulcha',
  'Pav Bhaji Set',
  'Thali Meals (South Indian)',
  'Sadya Thali',
  'Dahi Vada Set',
  'Chole Tikki Set',
  'Roti Sabzi',
  'Uttapam Set',
  'Vada Sambar',
  'Keema Pav',
  'Biryani Raita',
  'Chholar Dal with Luchi',
  'Daal Bafla',
  'Pithla Bhakri',
  'Dal Pakwan',
  'Zunka Bhakri'
);
COMMIT;
