import React, { useState } from "react";
import { Modal, Pressable, StyleProp, StyleSheet, Switch, Text, TextInput, TextInputProps, View, ViewStyle } from "react-native";

export const palette = { bg: "#FFFBF5", surface: "#FFFFFF", ink: "#231F25", muted: "#766F78", purple: "#8739D3", purpleSoft: "#F4EAFD", green: "#1FA563", amber: "#E89A24", red: "#E7465D", line: "#ECE5DC", beige: "#F5EFE7" };

export function FButton({ label, onPress, kind = "primary", disabled, style }: { label: string; onPress?: () => void; kind?: "primary" | "secondary" | "ghost" | "danger"; disabled?: boolean; style?: StyleProp<ViewStyle> }) {
  const buttonKind = { primary: s.primaryButton, secondary: s.secondaryButton, ghost: s.ghostButton, danger: s.dangerButton }[kind];
  const textKind = { primary: undefined, secondary: s.secondaryText, ghost: s.ghostText, danger: s.dangerText }[kind];
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, buttonKind, pressed && s.pressed, disabled && s.disabled, style]}><Text style={[s.buttonText, textKind]}>{label}</Text></Pressable>;
}
export function FChip({ label, selected, onPress }: { label: string; selected?: boolean; onPress?: () => void }) {
  return <Pressable onPress={onPress} style={[s.chip, selected && s.chipSelected]}><Text style={[s.chipText, selected && s.chipTextSelected]}>{label}</Text></Pressable>;
}
export function FInput(props: TextInputProps) { return <TextInput placeholderTextColor="#A79FA8" {...props} style={[s.input, props.style]} />; }
export function FSwitch({ value, onValueChange }: { value: boolean; onValueChange: (v: boolean) => void }) { return <Switch value={value} onValueChange={onValueChange} trackColor={{ false: "#DCD6CE", true: "#CFA7F1" }} thumbColor={value ? palette.purple : "#fff"} />; }
export function OTPInput({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <View style={s.otpRow}>{[0,1,2,3,4,5].map((i) => <Pressable key={i} style={s.otpCell}><Text>{value[i] ?? ""}</Text></Pressable>)}<TextInput value={value} onChangeText={(v) => onChange(v.replace(/\D/g, "").slice(0, 6))} keyboardType="number-pad" style={s.hidden} /></View>; }
export function Segmented({ options, value, onChange }: { options: string[]; value: string; onChange: (v: string) => void }) { return <View style={s.segment}>{options.map((x) => <Pressable key={x} onPress={() => onChange(x)} style={[s.segmentItem, value === x && s.segmentActive]}><Text style={[s.segmentText, value === x && s.segmentTextActive]}>{x}</Text></Pressable>)}</View>; }
export function Avatar({ initials = "AS" }: { initials?: string }) { return <View style={s.avatar}><Text style={s.avatarText}>{initials}</Text></View>; }
export function ProgressBar({ progress }: { progress: number }) { return <View style={s.progress}><View style={[s.progressFill, { width: `${Math.max(0, Math.min(1, progress)) * 100}%` }]} /></View>; }
export function Skeleton({ height = 18 }: { height?: number }) { return <View style={[s.skeleton, { height }]} />; }
export function StateCard({ icon, title, body, action }: { icon: string; title: string; body: string; action?: string }) { return <View style={s.state}><Text style={s.stateIcon}>{icon}</Text><Text style={s.stateTitle}>{title}</Text><Text style={s.stateBody}>{body}</Text>{action ? <FButton label={action} /> : null}</View>; }
export function Toast({ visible, text }: { visible: boolean; text: string }) { return visible ? <View style={s.toast}><Text style={s.toastText}>{text}</Text></View> : null; }
export function Sheet({ visible, onClose, children }: { visible: boolean; onClose: () => void; children: React.ReactNode }) { return <Modal transparent animationType="slide" visible={visible} onRequestClose={onClose}><Pressable style={s.scrim} onPress={onClose}><Pressable style={s.sheet}>{children}</Pressable></Pressable></Modal>; }

const s = StyleSheet.create({
  button: { minHeight: 50, paddingHorizontal: 20, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: palette.purple }, primaryButton: {}, secondaryButton: { backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.line }, ghostButton: { backgroundColor: "transparent" }, dangerButton: { backgroundColor: "#FFF0F1" }, buttonText: { color: "white", fontWeight: "700", fontSize: 15 }, secondaryText: { color: palette.ink }, ghostText: { color: palette.purple }, dangerText: { color: palette.red }, pressed: { opacity: .8, transform: [{ scale: .99 }] }, disabled: { opacity: .45 },
  chip: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 18, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.line }, chipSelected: { backgroundColor: palette.purple, borderColor: palette.purple }, chipText: { color: palette.muted, fontWeight: "600", fontSize: 12 }, chipTextSelected: { color: "white" },
  input: { minHeight: 48, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.line, borderRadius: 12, paddingHorizontal: 14, color: palette.ink }, otpRow: { flexDirection: "row", gap: 7 }, otpCell: { width: 42, height: 50, borderWidth: 1, borderColor: palette.line, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "white" }, hidden: { position: "absolute", opacity: 0 },
  segment: { flexDirection: "row", padding: 3, borderRadius: 11, backgroundColor: palette.beige, borderWidth: 1, borderColor: palette.line }, segmentItem: { flex: 1, minHeight: 38, alignItems: "center", justifyContent: "center", borderRadius: 8 }, segmentActive: { backgroundColor: palette.purple }, segmentText: { color: palette.muted, fontWeight: "600", fontSize: 13 }, segmentTextActive: { color: "white" }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#F7D8A8", alignItems: "center", justifyContent: "center" }, avatarText: { fontWeight: "800", color: "#8A4F16" }, progress: { height: 5, borderRadius: 3, backgroundColor: palette.line, overflow: "hidden" }, progressFill: { height: "100%", backgroundColor: palette.purple }, skeleton: { backgroundColor: "#EEE8E0", borderRadius: 9 }, state: { alignItems: "center", padding: 28, gap: 9 }, stateIcon: { fontSize: 36 }, stateTitle: { fontSize: 19, fontWeight: "800", color: palette.ink }, stateBody: { color: palette.muted, textAlign: "center" }, toast: { position: "absolute", bottom: 90, left: 24, right: 24, padding: 14, borderRadius: 12, backgroundColor: palette.ink, zIndex: 10 }, toastText: { color: "white", textAlign: "center", fontWeight: "600" }, scrim: { flex: 1, justifyContent: "flex-end", backgroundColor: "#0005" }, sheet: { backgroundColor: palette.bg, padding: 24, borderTopLeftRadius: 24, borderTopRightRadius: 24, minHeight: 220 },
});
