name: Backup to Google Drive Foofoo - v3
on: 
  workflow_dispatch:

jobs:
  drive-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create ZIP Archive
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          # Extracts just the repository name (e.g., "dotfiles") from the default GitHub variable
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          
          # Combines the repo name and timestamp for the final file name
          ZIP_NAME="${REPO_NAME}-backup-${TIMESTAMP}.zip"
          
          shopt -s dotglob
          zip -r $ZIP_NAME * -x "$ZIP_NAME"
          
          echo "FILENAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Upload to Google Drive via OAuth
        uses: AnshPrakash/google-drive-upload-action@v0.1.3-alpha
        with:
          client_id: ${{ secrets.GDRIVE_CLIENT_ID }}
          client_secret: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          file-to-upload: ${{ env.FILENAME }}
          upload-folder: 'GitHub Backups'
